### ISSUE TITLE
consideration for usage in docker-sync

### ISSUE THREAD

**Issue by EugenMayer** [deajan/osync#105]
Hey! Got told that your project actually works pretty well for a 2 way sync, similar to unison (https://github.com/EugenMayer/docker-sync/issues/418)

Could you clarify, what technology is used to watch for changes on OSX (if any)?

How is osync superior to unison in terms of robustness / performance under linux/osx - what is used to sync ( rsync? ) what is used to watch? Why is used to diff?

Is a file-index build at the start of the daemon?

Sorry for all the questions  - but for me considering osync i have to know what is underlying and what it actually gives the user.

Thank you!

**Comment by deajan** [comment]
Hi,
First of all, osync isn't superior to unison in any terms, it has different goals :)
It's designed as stateful sync, meaning that there is no necessity of a daemon running on both sides. it's normally triggered by a cron task.
It can be run as daemon, triggered upon file modifications (on initiator only) via inotify-tools under Linux or fswatch under OSX.

There is a file index built at the beginning and the end of any sync task
Sync itself relies heavily on ```rsync``` which is run multiple times, for file indexes and sync itself.
Diffs are basically done with ```comm``` tool.

Some of the cool stuff osync can do:
- time control (meaning after how much time should a sync be stopped)
- alert emails
- aborted sync resuming
- conflict files automatic backup and multiple backup
- deleted file backup
- automatic house cleaning of old backup files

Every release is tested on Linux, BSD, OSX, Windows (bash &cygwin &msys).
Hopefully I answered some of your questions :)

**Comment by EugenMayer** [comment]
Thank you @deajan for clarifying this. For docker-sync stateful sync is just way to slow and CPU intensive, i just suggest osync just has different goals which is fair enough!

Thank you for given me this insight!

**Comment by EugenMayer** [comment]
docker-sync tries to speed up local shares into containers. It has different ways, but the current one e.g. using OSFX and then unison on linux tries to dettach the actual host mount from the folder used by the application, while doing a 2 way sync. More on this see https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies#native_osx-osx

**Comment by deajan** [comment]
No problem, osync primary targets low bandwidth replication, where connection is often lost, thus the stateful mechanism.

I'm quite interested about the dockerr-sync goals, as they could give me some ideas for my osync2 implementation in python.
What's your current problem with unison ? Only portability ?

**Comment by EugenMayer** [comment]
Well nothing you have yet covered with osync at all - mostly the issues are behind acually detecting changes ( fswatch/macfsevent ) and good alternatives under linux with inotify. Beside that, unison can stop working when a huge amount of files get change instantly, like a git branch change - nothing you deal with, since you sync that after all those changes have finished, while unison starts syncing each subchange during the changes

**Comment by deajan** [comment]
Well at least I'll program sime git branch changes for osync2 unit tests :) Thanks
