### ISSUE TITLE
Watch target folder

### ISSUE THREAD

**Issue by gabzim** [deajan/osync#108]
Sometimes the target folder is located remotely, in which case osync obviously can't watch it, but why can't it watch a local target and a local initiator? I need to keep two local folders completely synced, is this possible? (And if possible, using a daemon instead of a cron task)

**Comment by deajan** [comment]
That's actually an excellent idea that can be quickly added to the current dev version.
I'm currently working on the osync-target-helper service which resolves remote watching too.

I'll reach out to you once this is done.

**Comment by arg20** [comment]
Awesome @deajan, thanks!

**Comment by deajan** [comment]
TARGET_SYNC_DIR declaration is bogus in helper.
Also, why not use actual osync as target helper service too ?

**Comment by deajan** [comment]
Is now available in latest master.
