### ISSUE TITLE
Add --prefix option for installation

### ISSUE THREAD

**Issue by jdeaton** [deajan/osync#111]
Allow placing osync/configuration files in non /usr/local/bin and /etc/osync locations. This would allow installation/configuration in a user's home directory for example.

**Comment by deajan** [comment]
Indeed this could be quite simple, as there's already a $FAKEROOT variable in the script.
I'll add this to next version.

**Comment by deajan** [comment]
```--prefix``` option has been added to current installer.

**Comment by YodaEmbedding** [comment]
I get this:

```bash
$ git clone https://github.com/deajan/osync
$ cd osync
$ bash install.sh --prefix="$HOME/.local/bin"
Must be run as root.
```

**Comment by deajan** [comment]
Thanks for reporting back.
You can safely use latest dev version, which should become v1.3 without any other modifications I hope.
