### ISSUE TITLE
~/.ssh/config entries do not work

### ISSUE THREAD

**Issue by bfrk** [deajan/osync#112]
In order to access my machine at work I need to go via an extra entry point machine. Also, my user name is different on the target machoine. To make access via ssh easier I have an entry in my .ssh/config:

```
Host *.bessy.de
  ServerAliveInterval 300
  User franksen
  ProxyCommand ssh gak@display.helmholtz-berlin.de netcat %h %p 2> /dev/null
```

So I can say

`ssh tiber`

and arrive at the correct machine with the appropriate user name.

Trying the same with osync.sh doesn't work:

```
ben@yuiitsu[1]:~/src>osync.sh --initiator=/home/ben/src/osync --target=ssh://tiber//home/franksen/src/osync                      
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Mon Jul 24 20:35:56 CEST 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [quicksync_task] launched as ben@yuiitsu (PID 5057)
ben@tiber.acc.bessy.de's password: 
```

Neither do `franksen@tiber` or `franksen@tiber.acc.bessy.de` work because I have to go via `gak@display.helmholtz-berlin.de`. At the moment I have no idea how to work around this limitation. It would be nice if .ssh/config would "just work" with osync.

**Comment by deajan** [comment]
Sorry, but this seems to be a rare usecase which I won't have time to adress in a short future.
You may look for SSH_CMD= line in osync.sh and see if you can modify it to fit your usage indeed.

**Comment by bfrk** [comment]
Ok, thanks for the quick response. I'll look somewhere else, perhaps do some shell hacking myself (using rsync).
