### ISSUE TITLE
OSync detects self as conflicting local instance

### ISSUE THREAD

**Issue by Rockstar04** [deajan/osync#113]
I am trying to sync two directories on a SFTP server. One is a local directory that is the SFTP users CHRoot'd home directory, and the other is a NFS mounted directory shared by servers processing the incoming data. Normally (90% of the time) osync fails with the error `There is already a local instance [27130@quicksync_task] of osync running for this replica. Cannot start.` Other times the process seems to run, but still throws and error at the end `Could not unlock local target replica.`.

Full Output: https://gist.github.com/Rockstar04/13c861f3f66f034302f09116d2d1bd69

**Comment by deajan** [comment]
Honestly I don't have a clue about what's going on here.
Before running osync, can you check that there is stale lockfile in ``/obscure_path/incoming/.osync_workdir/lock```
This lockfile normally contains a pid, which you should check if is running.

Also, if the file exists, you should try to delete it as chrooted user with ```rm -f /obscure_path/incoming/.osync_workdir/lock``` and ```/obscure_nfs_path/incoming/.osync_workdir/lock```

**Comment by Rockstar04** [comment]
I updated to the latest master and it ran without any errors or warnings on the first try. I'll close this, but if I run into the issue again I will reopen.

Thanks @deajan !

**Comment by deajan** [comment]
Thanks for letting know.
