### ISSUE TITLE
Is it safe to use osync for git repo?

### ISSUE THREAD

**Issue by ickc** [deajan/osync#114]
Hi, it seems this question hasn't been asked or mentioned anywhere: does anyone know if using osync to sync git repo is safe? e.g. what happens if the 2 sides has a different commits?

Thanks.

**Comment by deajan** [comment]
Git repos should work just like any other folders.
Conflictual files are backed up in .osync_workdir/backups, latest version is used.

**Comment by ickc** [comment]
Great. I'll try and let's see. Thanks.
