### ISSUE TITLE
Getting version from /etc/os-release should fail more gracefully

### ISSUE THREAD

**Issue by Shadowigor** [deajan/osync#116]
Starting `osync` gives me the following Error:

```text
TIME: 0 - Cannot get value for [VERSION] in config file [/etc/os-release].
```

My OS (Arch Linux) doesn't have a `VERSION` field in `/etc/os-release`:

```text
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

While `osync` runs through the sync process fine, it still finishes with `osync finished with errors.`. It doesn't break anything for me, but I still think, that this shouldn't be considered an error.

**Comment by deajan** [comment]
Last master should be more graceful when no version is found.

**Comment by Shadowigor** [comment]
Awesome!
