### ISSUE TITLE
Skipping Folders

### ISSUE THREAD

**Issue by crisward** [deajan/osync#118]
I need to skip a subfolder when syncing. 
Is this possible with osync? I couldn't find anything in the readme.

Thanks.

**Comment by deajan** [comment]
That's what exclude patterns are for. They work just the same as rsync exclude patterns.

**Comment by crisward** [comment]
I couldn't find anything in the docs (just searched for the word "exclude").
I also saw this file `exclude.list.example` but wasn't sure how to use it.

Thanks for the quick response.

**Comment by crisward** [comment]
env var RSYNC_EXCLUDE_FILES?

**Comment by crisward** [comment]
RSYNC_EXCLUDE_PATTERN seems to work.

Thanks.
