### ISSUE TITLE
inotifywait error in FreeBSD. 

### ISSUE THREAD

**Issue by emanzx** [deajan/osync#119]
Hi osync is throwing this error when I try to run it in monitor mode in FreeBSD. 

Fri Nov 17 15:00:36 MYT 2017 - -------------------------------------------------------------
Fri Nov 17 15:00:36 MYT 2017 - Fri Nov 17 15:00:36 MYT 2017 - osync 1.2 script begin.
Fri Nov 17 15:00:36 MYT 2017 - -------------------------------------------------------------
Fri Nov 17 15:00:36 MYT 2017 - Sync task [sync_bind_slave] launched as system@dnsvnode1 (PID 7906)
Fri Nov 17 15:00:36 MYT 2017 - #### Running osync in file monitor mode.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Fri Nov 17 15:00:36 MYT 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [sync_bind_slave] launched as system@dnsvnode1 (PID 7947)
TIME: 0 - Checking minimum disk space in local replica [/home/system/bind/etc/].
TIME: 0 - Checking minimum disk space in remote replica [/home/system/configs/bind/dnsvnode1/].
TIME: 3 - Starting synchronization task.
TIME: 3 - Creating initiator replica file list [/home/system/bind/etc/].
TIME: 3 - Creating target replica file list [/home/system/configs/bind/dnsvnode1/].
TIME: 5 - Creating initiator replica deleted file list.
TIME: 5 - Creating target replica deleted file list.
TIME: 5 - Updating target replica.
TIME: 6 - Updating target replica succeded.
TIME: 6 - Updating initiator replica.
TIME: 8 - Updating initiator replica succeded.
TIME: 8 - Propagating deletions to initiator replica.
TIME: 8 - Propagating deletions to target replica.
TIME: 9 - Creating initiator replica file list [/home/system/bind/etc/].
TIME: 9 - Creating target replica file list [/home/system/configs/bind/dnsvnode1/].
TIME: 10 - Finished synchronization task.
TIME: 10 - Running conflict backup cleanup.
TIME: 10 - Removing files older than 30 days on initiator replica for conflict backup deletion.
TIME: 10 - File cleanup complete on initiator replica.
TIME: 10 - Directory cleanup complete on initiator replica.
TIME: 11 - Removing files older than 30 days on target replica for conflict backup deletion.
TIME: 12 - Cleanup complete on target replica.
TIME: 12 - Running soft deletion cleanup.
TIME: 12 - Removing files older than 30 days on initiator replica for softdelete deletion.
TIME: 12 - File cleanup complete on initiator replica.
TIME: 12 - Directory cleanup complete on initiator replica.
TIME: 13 - Removing files older than 30 days on target replica for softdelete deletion.
TIME: 13 - Cleanup complete on target replica.
TIME: 15 - osync finished.
Fri Nov 17 15:00:51 MYT 2017 - #### Monitoring now.
include and exclude regexp cannot both be specified.
Fri Nov 17 15:00:51 MYT 2017 - #### inotify error  detected, waiting 60 seconds before running next sync.

I try to remove the --exclude but it just break the whole thing. any help?

**Comment by deajan** [comment]
On the line that states ```inotifywait $RSYNC_PATTERNS $RSYNC_PARTIAL_EXCLUDE --exclude "$OSYNC_DIR" -qq -r -e create -e modify -e delete -e move -e attrib --timeout "$MAX_WAIT" "$INITIATOR_SYNC_DIR" &```
Could you try to remove ```$RSYNC_PATTERNS``` ?
If it doesn't work, also remove ```$RSYNC_PARTIAL_EXCLUDE```

I don't have a FreeBSD to check right now. Does this work ?

**Comment by clawoflight** [comment]
@deajan inotify is a Linux extension. I'm pretty sure no other *NIX has it.

**Comment by deajan** [comment]
Nope, you may install it using ```pkg install inotify-tools```
The main difference is that the BSD version doesn't take include and exclude arguments toghether.
