### ISSUE TITLE
Failure to recognise existing osync task

### ISSUE THREAD

**Issue by andrewatfornax** [deajan/osync#121]
When running osync from a configuration file, an initial run is triggered using the --no-maxtime option, as this is a large initial sync.

However, the server has a crontab in place to trigger a sync every 5 minutes. For some time, this was fine - whenever the sync was triggered, it recognised that the initial run was in place. For example:

```
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Wed Nov 22 15:55:34 AEDT 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [SMB_SHARE_POINT_SYNC] launched as root@server (PID 87114)
TIME: 0 - Checking minimum disk space in local replica [/path/].
TIME: 0 - Checking minimum disk space in remote replica [/path/].
TIME: 1 - Starting synchronization task.
TIME: 1 - Creating initiator replica file list [/opt/hybris/hybris/data/media/].
TIME: 1 - Creating target replica file list [/opt/hybris/hybris/data/media/].
TIME: 59 - Current tasks still running with pids [87232,87233].
TIME: 119 - Current tasks still running with pids [87232,87233].
TIME: 179 - Current tasks still running with pids [87232,87233].
TIME: 239 - Current tasks still running with pids [87232,87233].
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Wed Nov 22 16:00:01 AEDT 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [SMB_SHARE_POINT_SYNC] launched as root@server (PID 111005)
TIME: 1 - Checking minimum disk space in local replica [/path/].
TIME: 1 - (CRITICAL):There is already a local instance [87114@SMB_SHARE_POINT_SYNC] of osync running for this replica. Cannot start.
TIME: 1 - (CRITICAL):Remote lock handling failed.
TIME: 2 - (CRITICAL):Cancelling task.
TIME: 2 - (ERROR):osync finished with errors.
TIME: 299 - Current tasks still running with pids [87232,87233].
TIME: 359 - Current tasks still running with pids [87232,87233].
```

and so on. 

However, then this happened:

```
TIME: 839 - Current tasks still running with pids [87232,87233].
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Wed Nov 22 16:10:01 AEDT 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [SMB_SHARE_POINT_SYNC] launched as root@server (PID 34206)
TIME: 0 - Checking minimum disk space in local replica [/path/].
TIME: 1 - Starting synchronization task.
TIME: 1 - Creating initiator replica file list [/path/].
TIME: 1 - Creating target replica file list [/path/].
TIME: 899 - Current tasks still running with pids [87232,87233].
TIME: 59 - Current tasks still running with pids [34482,34483].
```

At this point, the sync is now running twice.

This then continues, with all future crontab based executions of osync failing to recognise the already running instance of osync.

This can be worked around, by not having the crontab in place until after the initial sync, but this should not happen.

**Comment by deajan** [comment]
This will be quite hard to diagnose.
In the meantime, can you elaborate a bit. How many runs were successfully aborted because of an already existing lock before osync began to run twice ?

Also, would you mind running with current master 1.2.2-dev version ?

**Comment by andrewatfornax** [comment]
HI @deajan,

Yes, diagnosing will be difficult - potentially impossible. 

I can confirm that TWO runs were aborted successfully - the cronjob was triggering osync every 5 minutes, so, there was the run that happened some time between 239 seconds and 299 seconds (of the original sync), which aborted correctly, and then another 5 minutes later, and then it was the third run some time between 839 seconds and 899 second, which did not abort as it should have.

Unfortunately, on the system this was happening, I've had to move on from osync (not my systems), because the client wanted to sync two Azure SMB share mounts, which greatly restrict options for setting ownership, modification time, etc. and I could not figure out a combination of options to get osync to work without the ability to set the modification time on the files.

**Comment by deajan** [comment]
SMB share mounts can be synced by disabling de ```PRESERVE_xxxxx``` values in config files.
Running on cross filesystems, you may also set ```RSYNC_OPTIONAL_ARGS=--modify-window=2```

Anyway, I will keep this open as a bug until I get time to resolve the issue.
Thanks for reporting.

**Comment by andrewatfornax** [comment]
Hi @deajan - ah, thanks - I had turned off all the PRESERVE_ options, but not tried the modifiy-window option. I will take a look - if that works, then perhaps we can re-test on this system! 

I will let you know.

**Comment by andrewatfornax** [comment]
Hi @deajan,

I know this is getting off topic, but those options still don't stop osync from trying to set times on files.

```
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Thu Nov 23 10:19:44 AEDT 2017 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [SMB_SHARE_POINT_SYNC] launched as root@system (PID 25134)
TIME: 0 - Checking minimum disk space in local replica [/path/].
TIME: 1 - Starting synchronization task.
TIME: 1 - Creating initiator replica file list [/path/].
TIME: 1 - Creating target replica file list [/path/].
TIME: 12102 - Creating initiator replica deleted file list.
TIME: 12102 - Creating target replica deleted file list.
TIME: 12102 - Updating target replica.
TIME: 19452 - (CRITICAL):Updating target replica failed. Stopping execution.
TIME: 19452 - (WARN):Command was [/bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --modify-window=2 --partial --partial-dir=".osync_workdir/_partial" --no-whole-file    --checksum -u -e "/bin/ssh -C -i /path/to/id_rsa  -p 22" --backup --backup-dir=".osync_workdir/backup" --suffix .2017.11.23-10.19.44 --exclude ".osync_workdir"  --exclude=".osync_workdir/_partial" --exclude-from="/path/.osync_workdir/state/initiator-deleted-list-SMB_SHARE_POINT_SYNC" --exclude-from="/path/.osync_workdir/state/target-deleted-list-SMB_SHARE_POINT_SYNC" "/path/" user@remote:"/path/" >> /tmp/osync.update.target.25134.20171123T101944.053207336 2>&1].
TIME: 19452 - Rsync output:
```

and then a lot of errors of the form:

```
rsync: failed to set times on "/path/dir1/dir2/dir3/dir4": Operation not permitted (1)
```

and finally

```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
TIME: 19453 - (ERROR):osync finished with errors.
```

**Comment by deajan** [comment]
Heck of a problem, what's the underlying FS ?
Please try ```RSYNC_OPTIONAL_ARGS=--modify-window=2 --omit-dir-times```

**Comment by andrewatfornax** [comment]
It's a RHEL 7.2 system.

Thanks, I will try the --omit-dir-times options and see how that goes!

**Comment by deajan** [comment]
Btw, I could replicate the locking issue.
Fix is now in master.

**Comment by andrewatfornax** [comment]
Thats great, thanks @deajan!

The rsync --omit-dir-times option did the trick, combined with turning off the PRESERVE_ options, when syncing between two SMB share points mounted on a Linux system as well.

Thank you!
