### ISSUE TITLE
Manual Install ?

### ISSUE THREAD

**Issue by stepgr** [deajan/osync#125]
Hi,

I'm having trouble when running the install script through cygwin64  on windows server 2003r2 machine.
The install script reports : 

>>Can't detect initV or systemd. Service files won't be installed. You can still run osync manually or via >>cron.
>>cp: cannot stat ‘/osync.sh’: No such file or directory
>>Cannot copy [osync.sh] to [/usr/local/bin]. Make sure to run install script in the directory containing all >>other files.
>>Also make sure you have permissions to write to [/usr/local/bin].

How to install manually ? what files are needed ?

thanks in advance

**Comment by deajan** [comment]
Hello, install script is for Linux only indeed.
On cygwin, osync.sh and a config file should be enough, juste copy them and make them executable.

**Comment by stepgr** [comment]
I guess no one has tried windows to linux  and vice versa with this tool before  and I'm the guinea pig then.
Anyway I going to try and let you know .  Config file goes to /etc of cygwin and executable in /bin then right ?

**Comment by deajan** [comment]
Actually tried, since I couldn't test cygwin without doing so. Windows needs to be the initiator indeed, unless you can install an ssh server on windows which could then become a target.
Both files can go wherever you like.
