### ISSUE TITLE
Cannot get value for [VERSION] in config file [/etc/os-release].

### ISSUE THREAD

**Issue by nglgzz** [deajan/osync#126]
Hi, I'm trying to run this script on Arch. The syncing seems to work fine, but I get the error mentioned above. Below is the content of my `/etc/os-release` file.

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

And the result of `uname -a`

```
$ uname -a
Linux zxcv 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux
```

**Comment by deajan** [comment]
Actually this has been corrected in #116 in a dev branch. Master is now up to date.

**Comment by nglgzz** [comment]
Thank you for your quick response!

I tried with master (I was on stable before), the error is not showing, but the script exits with status code 2. Below is the output I get from running the command and checking the exit status code.

```
$ osync.sh \
    --initiator="$LOCAL" \
    --target="$REMOTE" \
    --rsakey="$KEY_PATH" \
    --errors-only; echo "Exit status code: $?"
TIME: 0 - This is an unstable dev build [2017112302]. Please use with caution.
TIME: 0 - Sat Dec 30 20:45:16 CET 2017 - osync 1.2.2-dev script begin.
TIME: 12 - osync finished with warnings.
Exit status code: 2
```

I'm pointing this out because I'm using a systemd timer to schedule the execution of osync, and when looking at the logs, or at the status of the service, I get a prominent error message and it says that the service failed, even though everything went fine.

**Comment by deajan** [comment]
Because it's a developpment branch which isn't always stable, there is a warning about it.
You may disable that warning by changing line ```IS_STABLE=no``` to ```IS_STABLE=yes``` in osync.sh header.
Current master is pretty stable except for some compat tests with FreeBSD and MacOS.

**Comment by nglgzz** [comment]
Yaay that did it, thank you!

When is this going to be on the stable branch? Just to know if I should checkout the stable branch or add the workaround on my setup script.

Also thank you a lot for this project, I've been trying different things for syncing my projects between computers, and osync is the first one that seems to work seamlessly.

**Comment by deajan** [comment]
As I said, the current master branch is already pretty stable as of today. You should prefer it to v1.2 release. This may change in the future, before some of the changes I make can be disruptive, but today's version is simply a bugfixed v1.2 branch.

Also, thank you for your kind words.

**Comment by GAZ082** [comment]
Hi. Having same issue on Arch.:
PROGRAM_VERSION=1.2
PROGRAM_BUILD=2017032101

IS_STABLE is alredy in yes.

![image](https://user-images.githubusercontent.com/100194/71634268-58823200-2bf9-11ea-943a-6070e6da6442.png)

**Comment by deajan** [comment]
@GAZ082 Well as I said above, please user current master and not 1.2 release which has that issue
