### ISSUE TITLE
does not respect automout

### ISSUE THREAD

**Issue by dmorilha** [deajan/osync#129]
systemd automount takes a while to mount. osync.sh jumps straight ahead and starts syncing with an empty folder (deleting all the files)

**Comment by deajan** [comment]
Well you have to modify the unit file adding ```RequiresMountsFor=[mountpoint]```.
Nothing wrong with the software itself IMO.

**Comment by dmorilha** [comment]
I'll give it a try...

**Comment by dmorilha** [comment]
worked, thanks for the clue!
