### ISSUE TITLE
False positive error detection on ssh banner text

### ISSUE THREAD

**Issue by curby** [deajan/osync#131]
Hi there, I'm running osync on a corporate network, where computers have a login banner notifying potential users that all activity may be monitored.  The banner starts with this line:

```**WARNING**WARNING**WARNING**WARNING**WARNING**```

I'm pretty sure osync is seeing that, interpreting it as an rsync error, and propagating the error up so that it ends up sending an alert email, etc.

Any way to make the error detection "smarter" so it doesn't falsely trigger on an SSH banner?  Thanks!

EDIT: This shows up in the osync log as:

```
(ERROR):**WARNING**WARNING**WARNING**WARNING**WARNING**
...
...
...
TIME: 4 - (ERROR):osync finished with errors.
```

As far as I can tell, it's the only thing that's flagged as an error.  The sync itself completes successfully.

**Comment by deajan** [comment]
I think current master already has a fix for this. Can you try ?

**Comment by curby** [comment]
I had originally installed the stable branch.  The master doesn't seem to have the problem described above, but it has other critical issues that might be masking this one.  

See #132

**Comment by deajan** [comment]
Tried with both really large banner and motd, works in current master.
