### ISSUE TITLE
master branch doesn't like macOS Sierra sed

### ISSUE THREAD

**Issue by curby** [deajan/osync#132]
It reports the following multiple times:

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

It also seems to delete everything from both initiator and target, perhaps because of the sed issues.

This is on macOS Sierra 10.12.6.  The stable branch doesn't exhibit this issue.

**Comment by deajan** [comment]
Known on project compatibility un github.
You may change sed -r by sed -E in osync.sh to resolve this while I don't have a patch ready.

**Comment by deajan** [comment]
Fixed in https://github.com/deajan/osync/commit/d8b30d77110c8153e88d3f648ef935dec9518998
