### ISSUE TITLE
A lot of spam to standard error about not being able to preserve permissions, times, etc.

### ISSUE THREAD

**Issue by kozross** [deajan/osync#133]
I'm running osync on Termux, and I keep getting messages of the form:

    mv: can't preserve times of 'data/data/com.termux/files/home/storage/shared/Books/.osync_workdir/state/target-tree-after-books_sync': Operation not permitted

I told osync.sh to not bother preserving anything when I first got these errors (via a config file), but I still keep getting them, even when I run as --silent. This doesn't _seem_ to affect its operations, but I don't understand why these show up.

**Comment by deajan** [comment]
osync launches some subcommands like mv. Instead of just ignoring subcommand errors, I chose to show them in order to know when something goes wrong. 
Altough I did test osync on Termux, I never saw that problem.
Can you send me a full debug log like:
```_DEBUG=yes osync.sh [options```

Also, what termux version are you using ?
At last, do you try to sync different FS ?

**Comment by kozross** [comment]
Upon further investigation, I discovered these issues stem from me wanting to sync directories that aren't in Termux's own storage (Android directories like Documents and Music). This has been resolved by running ``osync.sh`` as root.

**Comment by roguh** [comment]
For anyone else having a similar problem, I worked around it without root access by preventing osync from synchronizing permissions and rsync from sync'ing directory modification times:

```
PRESERVE_ACL=no
PRESERVE_XATTR=no 
PRESERVE_OWNER=no
PRESERVE_GROUP=no
PRESERVE_PERMISSIONS=no
PRESERVE_EXECUTABILITY=no
RSYNC_ARGS='--omit-dir-times '
```

Using `--omit-dir-times` may have unintended consequences.
