### ISSUE TITLE
Backticks and double spaces in path and filenames

### ISSUE THREAD

**Issue by grandgeorg** [deajan/osync#135]
We have an issue with osync:

It cannot handle backticks and double spaces in file- and directory names correctly.
We are running on Ubuntu 16.04 LTS and osync 1.2 in daemon mode (with inotify).

If we have a filename like ```Barney`s Lookbook``` osnyc is producing errors especially when deleting files.
Protocol says something along the following lines:

```
TIME: 141 - (ERROR):Error while executing cleanup on remote target replica.
TIME: 141 - (WARN):Command output:
bash: -c: line 0: syntax error near unexpected token `fi'
bash: -c: line 0: `export file="/cloud/.osync_workdir/backup/Fotos/2009-2014/14.11. Barney`s Lookbook"; if [ false == true ]; then echo "On "target" will delete directory /cloud/.osync_workdir/backup/Fotos/2009-2014/14.11. Barney`s Lookbook"; fi; if [ false == false ]; then rm -rf "/cloud/.osync_workdir/backup/Fotos/2009-2014/14.11. Barney`s Lookbook"; fi'
```

The other problem is with double spaces in filenames.  
If we have filename like ```foo  (98).jpg``` (there are two spaces between ```foo``` and ```(98).jpg```) and delete this file on source or target server after next sync the file is present again on both sides.

**Comment by deajan** [comment]
Indeed, I thought all the special characters were well handled. I can confirm the backtick thing, but I can't reproduce the double space filename issue. Do you have any logs for this ? Can you run with _DEBUG=yes osync.sh ?
Also, could you try current master please ?

**Comment by grandgeorg** [comment]
I did some further testing on the double space issue:

I installed the current master branch. There the double space issue does not occur.
Instead there is an **error in osync.sh**:

```
/usr/local/bin/osync.sh: line 468: CheckRFC822: command not found
/usr/local/bin/osync.sh: line 468: [: -ne: unary operator expected
```
This due to a typo. Line 468 must be:
```
if [ $(checkRFC822 "$i") -ne 1 ]; then
```
So checkRFC822 starting with **lower case**.

The sync works fine...

For the test I deleted a previously synced file ```/data/test/foo  (3).jpg```

osync on **master** log says:
```
TIME: 5 - Deleting [/data/test/foo  (3).jpg].
```
and everything is fine.
osync from **stable** branch says:
```
...
TIME: 3 - Updating target replica.
TIME: 4 - List:
.d..t...... ./
TIME: 4 - Updating target replica succeded.
TIME: 4 - Updating initiator replica.
TIME: 5 - List:
>f+++++++++ foo  (3).jpg
TIME: 5 - Updating initiator replica succeded.
TIME: 5 - Propagating deletions to initiator replica.
TIME: 5 - Propagating deletions to target replica.
...
```
And the file is falsely present again ...

**Comment by deajan** [comment]
Thanks for the detailed report.
I have updated the current master with the typo fix among other fixes.

I'll investigate the backtick issue these days.

**Comment by deajan** [comment]
Updated master branch with a fix for the backticks.
Could you have a testrun ?
