### ISSUE TITLE
Some variables are set incorrectly when not using a config file

### ISSUE THREAD

**Issue by roguh** [deajan/osync#137]
`MIN_WAIT` is set to 30 no matter what the environment is.
`MAX_EXEC_TIME_PER_CMD_BEFORE` and `MAX_EXEC_TIME_PER_CMD_AFTER` are not set to default values of 0 like other MAX_EXEC_TIME variables are.

This means `MIN_WAIT`, `LOCAL_RUN_BEFORE_CMD`, and `LOCAL_RUN_AFTER_CMD` don't work when set using the command line instead of a config file:

```
MIN_WAIT=3 LOCAL_RUN_BEFORE_CMD=cmd osync.sh
```

**Comment by roguh** [comment]
PR #136 should fix these problems

**Comment by deajan** [comment]
Well most of these variables are inteded to be used in service mode, which requires a config file.
Why would you need MIN_WAIT when not running osync as service ?

**Comment by roguh** [comment]
The file watching features are useful for users on systems without the permissions or ability to create a service. In my case, that's the Android app Termux. I have access to bash and rsync, but no way run osync as a service.

I execute the program with `--on-changes` after sourcing my config file. I didn't want to use a complete config file when it seemed osync set default values of variables anyway.

Now I see osync sources all variables in the config file, while requiring that all variables are present. I might just use a config file as intended, but it might be worth considering the value of being able to use a minimal config file where not all variables are set.

**Comment by deajan** [comment]
Fair enough, I didn't intend to have ```--on-changes``` run on commandline.
I'll check your PR for merging.
Thanks.

**Comment by roguh** [comment]
Thank you for this very portable project. Beats getting Unison running properly.
