### ISSUE TITLE
daemon mode realtime problem

### ISSUE THREAD

**Issue by sandr2013** [deajan/osync#138]
when using daemon mode ,osync-srv probablay delay 10s.While using osync.sh,it execes quickly.Is there some config to resolve  the daemon mode delay pro?

**Comment by deajan** [comment]
osync is a stateful sync software that isn't supposed to be realtime, so, no.
You can adjust MIN_WAIT in config file to lower time between two service sync runs, but you'll trade time for cpu usage.

**Comment by sandr2013** [comment]
Got it.Thanks!
