### ISSUE TITLE
OpenRC support

### ISSUE THREAD

**Issue by kozross** [deajan/osync#140]
It'd be really great to have support for OpenRC init scripts for osync.

**Comment by deajan** [comment]
Isn't OpenRC a drop-in replacement for initV ? osync already supports initV style scripts.

**Comment by kozross** [comment]
Unfortunately the provided ``osync-srv`` does not properly work with OpenRC as-is. OpenRC will execute it fine, but won't work on startup and can't be properly monitored. The details are [here][1] - unfortunately, I'm not knowledgeable about OpenRC and can't contribute to this much. It took me this long just to dig these details up!

[1]: https://wiki.gentoo.org/wiki/Handbook:X86/Working/Initscripts#Writing_initscripts
