### ISSUE TITLE
FEATURE REQUEST: minimally detailed output

### ISSUE THREAD

**Issue by senorsmile** [deajan/osync#150]
I have a few things that I would like to see here, but I'm not sure the best way to suggest they be implemented.  Maybe, each of the following could be disabled/enabled individually?!?

- output number of files changed on each side
- output changed files without verbose flag (as I don't necessarily care about the status within the job, only number of files transferred in either direction and what those files were)

Right now, I enable the LOGFILE for full output to a custom location, and pipe the output of the run to get something like: 

```
    eval \
      ${env_opts[@]} \
      osync.sh \
      ${osync_opts[@]} \
      | egrep '(Number of|Sync task)'
```

It's not exactly what I'd like to see on a run, but it's good enough.

**Comment by deajan** [comment]
Have you tried --summary, --log-conflicts and --silent on latest master ?

**Comment by senorsmile** [comment]
I am running on master:

```
* fa64c49 - (HEAD -> master, origin/master, origin/HEAD) Added EscapeDoubleQuotes function (3 days ago) <deajan>
```

That gives me zero output to the console.  

There is a new section that appears in the log file that looks perfect though: 

```
...
Attrib updates: INITIATOR << >> TARGET
File transfers: INITIATOR << >> TARGET (may include file ownership and timestamp attributes)
+ >> //root/osync_files/financial/./
+ >> //root/osync_files/financial/test_delete_me.txt
File deletions: INITIATOR << >> TARGET
...
```

If just that was output to the console, that would be good enough.

**Comment by deajan** [comment]
Sorry I do not understand what you want.
If you only want to output the file changes, try running with ` --summary --errors-only --no-prefix`
While running on master, change "IS_STABLE=no" to "IS_STABLE=yes" in osync.sh in order to remove the warning.
Be aware that errors and warnings will still be shown.

**Comment by senorsmile** [comment]
Ah, that combination is perfect!  Marking this as closed.
