### ISSUE TITLE
Stuck on "Updating Initiator Replica"

### ISSUE THREAD

**Issue by zioth** [deajan/osync#168]
**Describe the bug**
Most of the time, when I run osync, the target replica is updated without a problem. Then, osync gets stuck on "Updating initiator replica" until it times out (after half an hour or so). I have debugging turned on, but there is no useful output -- no file list, no errors or warnings, nothing until it times out.

If there's any way to increase debug output, I'd be happy to try it and give you useful logs.

The command I run is:
`_DEBUG=yes; osync.sh osync.conf --verbose`

Running `debug_osync.sh` doesn't provide any additional output.

Logs (I've replaced sensitive information with `...`:
```
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sun May 26 20:44:23 CDT 2019 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [...] launched as ... (PID 32553)
TIME: 1 - Checking minimum disk space in local replica [/Users/.../Dropbox/.../].
TIME: 0 - Checking minimum disk space in remote replica [/home/.../public_html/].
df: Warning: cannot read table of mounted file systems: No such file or directory
TIME: 5 - Starting synchronization task.
TIME: 5 - (WARN):Will not resume aborted execution. Too many resume tries [2].
TIME: 5 - Creating initiator replica file list [/Users/.../Dropbox/.../].
TIME: 5 - Creating target replica file list [/home/.../public_html/].
TIME: 20 - Creating initiator replica deleted file list.
TIME: 20 - Creating target replica deleted file list.
TIME: 21 - Updating target replica.
TIME: 23 - :List:
.d..t.... data/locks/
<f.st.... data/meta/_dokuwiki.changes
<f..t.... data/meta/_dokuwiki.changes.trimmed
TIME: 23 - Updating target replica succeded.
TIME: 23 - Updating initiator replica.
TIME: 1800 - Current tasks still running with pids [34255].
...exited with ctrl+c here...
TIME: 1868 - (WARN): /!\ WARNING: Manual exit of osync is really not recommended. Sync will be in inconsistent state.
TIME: 1868 - (WARN): /!\ WARNING: If you are sure, please hit CTRL+C another time to quit.
TIME: 1868 - (CRITICAL):Updating initiator replica failed. Stopping execution.
TIME: 1868 - (WARN):Command was [/usr/bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file   -p -o -g --executability  -u -i -e "/usr/bin/ssh -C -i /Users/.../.ssh/id_rsa  -p 2200" --backup --backup-dir=".osync_workdir/backup" --exclude ".osync_workdir" --exclude="*.DS_Store*" --exclude="data/cache/*" --exclude="data/tmp/*" --exclude=".idea"  --exclude-from="/Users/.../Dropbox/.../.osync_workdir/state/initiator-deleted-list-..." --exclude-from="/Users/.../Dropbox/.../.osync_workdir/state/target-deleted-list-..." ...@....com:"/home/.../public_html/" "/Users/.../Dropbox/.../" >> /tmp/osync.update.initiator.32553.20190526T204423.N 2>&1].
TIME: 1868 - Rsync output:
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/rsync.c(244) [generator=2.6.9]rsync error: received SIGUSR1 (code 19) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(1201) [receiver=2.6.9]
TIME: 1870 - (ERROR):osync finished with errors.
```

**Comment by deajan** [comment]
The log message at 1800 seconds is not a timeout, but a message to say "i'm still alive doing my job".
How much data is on the target ? What's the link bandwidth between initiator and target ?
Depending on those, it might take more than a half hour to sync files.

**Comment by zioth** [comment]
> The log message at 1800 seconds is not a timeout, but a message to say "i'm still alive doing my job".
> How much data is on the target ? What's the link bandwidth between initiator and target ?
> Depending on those, it might take more than a half hour to sync files.

The changelist is very small. Probably only a few hundred KB of files need to be synced. Even if I synced the entire site (minus exclusions), it would be on the order of 50MB, which should only take a few minutes at most.

The job does eventually time out, after 12169 seconds (more than 3 hours), and it claims to have downloaded only half a MB, which, for that timeframe, could just be a whole lot of pings or connection handshakes. Here's the error:
```
TIME: 12169 - \e[33mMax soft execution time exceeded for task [Sync] with pids [52103].\e[0m
TIME: 12169 - Sent mail using mail command.
TIME: 12169 - \e[91mMax hard execution time exceeded for task [Sync] with pids [52103]. Stopping task execution.\e[0m
TIME: 12169 - \e[1;33;41mUpdating initiator replica failed. Stopping execution.\e[0m
TIME: 12169 - Rsync output:
rsync: connection unexpectedly closed (548636 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (548636 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [generator=2.6.9]
TIME: 12169 - Task with pid [52103] stopped successfully.
TIME: 12169 - Sent mail using mail command.
TIME: 12172 - \e[91mosync finished with errors.\e[0m
TIME: 12172 - Sent mail using mail command.
```

I could try running the rsync command directly, but I don't want to risk osync getting out of sync and forgetting files.

**Comment by deajan** [comment]
Well, from what I see, there might be link problem between your initiator and target.
Do you have any link loss statistics (FEC errors, ping timeouts...) ?

osync does simply run an rsync command which it waits for, and it seems stuck.
Running with DEBUG=yes osync.sh (without the semicolon) should give you that exact rsync command.

Btw, I noticed that your rsync implementation is REALLY outdated (like 2.6.9 is from november 2006).
Can you give me the output of the following commands please ?
```
rsync --verison
/usr/bin/rsync --version
/usr/local/bin/rsync --version
type rsync
```

I suspect you're running the initiator on Mac, and target on maybe something else ?
If on Mac, you might have installed rsync with brew ?
If so, there might exist multiple versions (old and new ones).

**Comment by zioth** [comment]
Thanks. I updated rsync to 3.1.3 (confirmed -- both `type` and `which` confirm I'm using the right version, and `RSYNC_REMOTE_PATH` is not set). Then I tried running rsync directly. Some of the time, it was only copying about 2KB per second, but it then sped up and finished the 559MB sync in 5 minutes. That was for the whole site.

osync was running at the same time, and after 20 minutes, has not finished copying the <1MB it has to copy.

I don't think it's a network issue, because,

- osync and rsync were running simultaneously, and rsync was able to copy half a gigabyte.
- `ping` shows no issues.
- Updating the target always succeeds. Only the initiator fails.

Another strange thing I noticed, is that the output file `/tmp/osync.update.initiator.2843.20190527T110635.N` is empty.

For rsync, I removed these parameters:

- --rsync-path
- --backup
- --backup-dir
- --exclude-from (the deleted lists, which are empty anyway)

Is it possible that osync's data is corrupt somehow? If so, how do I reset it? Delete the `.osync-workdir` directories on target and initiator?

**Comment by deajan** [comment]
You still didn't answer my questions. It's difficult to help you without any context.
I have no idea what system you're running on, I have no debug logs, I don't have any idea what the commands I gave you output.

You did run the rsync command, you should have left the command the same and remove one by one the four commands you listed in order to know which one does not work on your system.

Also, please update to latest osync 1.3 beta3 since I won't debug the old version.

**Comment by zioth** [comment]
Sorry. I thought I did answer your questions:

- No ping timeouts.
- Based on rsync, ssh and ping performance, I don't believe there are FEC errors, but I haven't measured it.
- Yes, I'm on MacOS.
- The target is linux, but I'm not sure which specific version. It's a web host running rsync 3.1.2.
- Locally, I'm running rsync 3.1.3 (after upgrading it today). It's in /usr/local/bin/rsync. `which` and `type` return the correct version, from that location. The copy in /usr/bin/rsync is still the old 2.1.6 version, but my paths are ordered correctly, so that version should not be used.
- There are no debug logs, other than what I posted above. Maybe I'm not looking in the right place. Is there another log somewhere, other than the one that's emailed after osync completes?

I think that covers everything you asked. Let me know if I missed anything.

I don't have time right now, but later, I can try rsync with some of the other options. I was just concerned that I might corrupt osync's state if I used --backup, but I guess I can just set it to a different path, or back up the original.

**Comment by zioth** [comment]
The problem is `--backup`. rsync hangs on "receiving incremental file list." Since I can now get rsync to hang, this is clearly not an osync issue, so I'll close this ticket.

Thanks for your help!

**Comment by deajan** [comment]
Thanks for the report.
In order to document this, can you please tell me which version of MacOS you're using ?

**Comment by zioth** [comment]
Mojave.

An osync option to enable the -vvv rsync flag would have been useful for debugging this. Strangely, using that flag just made rsync work with --backup, so something must be going on with my web host or MacOS.

**Comment by zioth** [comment]
Oh, and I recently (after I first reported this ticket) started getting these errors when I run osync.
```
\e[45m/!\ ERROR in /usr/local/bin/osync.sh: Near line 713, exit code 1\e[0m
\e[45m/!\ ERROR in /usr/local/bin/osync.sh: Near line 713, exit code 1\e[0m
\e[45m/!\ ERROR in /usr/local/bin/osync.sh: Near line 709, exit code 1\e[0m
```

**Comment by deajan** [comment]
This is what you get when environment variable _DEBUG=yes
Try an ```echo $_DEBUG```.
As I said, you should run debug like ```_DEBUG=yes /usr/local/bin/osync.sh``` but you added a semicolon, which made the change for your whole current shell.

**Comment by zioth** [comment]
I did make the change to remove the semicolon. It increased output, but not as much as `-vvv`. Doesn't matter though. osync config lets you add optional params, so I put `-vvv` there.

**Comment by deajan** [comment]
Thanks for your reporting.
I'll have a quick note about Mac and --backup switch.
You may remove the --backup switch by setting CONFLICT_BACKUP=no in config file.
