### ISSUE TITLE
[question] beta PKGBUILD

### ISSUE THREAD

**Issue by ITwrx** [deajan/osync#170]
hi,
i tried to tweak the osync AUR PKGBUILD to use the latest beta 

https://pastebin.com/6uUSnY0N

i named the extracted directory the same as the package name in my PKGBUILD if that matters.

but the build is failing:
 ```
makepkg
==> Making package: osync-1.3-beta3 v1.3-1 (Fri 05 Jul 2019 11:51:33 PM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.3-beta3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    253      0 --:--:-- --:--:-- --:--:--   253
100  247k    0  247k    0     0   171k      0 --:--:--  0:00:01 --:--:--  263k
==> Validating source files with md5sums...
    v1.3-beta3.tar.gz ... Skipped
==> Extracting sources...
  -> Extracting v1.3-beta3.tar.gz with bsdtar
==> Starting prepare()...
==> Entering fakeroot environment...
==> Starting package()...
mkdir: cannot create directory '/etc/osync': Permission denied
2019-07-05 23:51:36 - Cannot create directory [/etc/osync].
==> ERROR: A failure occurred in package().
    Aborting...
```
building using the normal AUR package works.

what am i doing wrong?
thanks

**Comment by deajan** [comment]
Hello,

I'm not the author of the AUR PKGBUILD files, so I won't be of great help here.
If I'd have to guess, I'd say that the $FAKEROOT variable isn't filled, which is supposed to replace /etc/osync with something like /buildroot/etc/osync.

**Comment by ITwrx** [comment]
thanks. it does look to have something to do with this. 

i tried changing the fakeroot line to: 
`echo n | FAKEROOT="/Downloads/AUR/osync-1.3-beta3/" bash ./install.sh > /dev/null`

which is my build dir, but that didn't work (same error) either. i think my understanding of makepkg is lacking...

**Comment by deajan** [comment]
Can you produce the output of the command ? Maybe something fishy with install.sh here.

**Comment by Shadowigor** [comment]
Yes, it's a bug of `install.sh`. On line 423 is sets the `FAKEROOT` variable to an empty string.

**Comment by ITwrx** [comment]
`==> Making package: osync-1.3-beta3 v1.3-1 (Mon 08 Jul 2019 11:29:29 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v1.3-beta3.tar.gz
==> Validating source files with md5sums...
    v1.3-beta3.tar.gz ... Skipped
==> Extracting sources...
  -> Extracting v1.3-beta3.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
mkdir: cannot create directory '/etc/osync': Permission denied
2019-07-08 11:29:30 - Cannot create directory [/etc/osync].
==> ERROR: A failure occurred in package().
    Aborting...`

**Comment by Shadowigor** [comment]
After taking a second look, it appears that the `FAKEROOT` environment variable has been replaced with a `--prefix` command line switch. You could try using that instead.

**Comment by deajan** [comment]
@Shadowigor Sorry for bothering you with this. I didn't expect to put some effort in AUR package that before v1.3 final release. Thanks for your insight.

**Comment by Shadowigor** [comment]
No problem, let's just hope one of us remembers to change the PKGBUILD for the 1.3 release ^^

**Comment by ITwrx** [comment]
i'm not understanding where/how to use the "--prefix" command line switch

**Comment by Shadowigor** [comment]
Change this:

```bash
echo n | FAKEROOT="$pkgdir" bash ./install.sh > /dev/null
```

to this

```bash
echo n | bash ./install.sh --prefix="$pkgdir" > /dev/null
```

**Comment by ITwrx** [comment]
thanks! i doubt i was going to figure that out. :) it built fine now.
