### ISSUE TITLE
/tmp and permission issues on Mac OS

### ISSUE THREAD

**Issue by valankar** [deajan/osync#175]
**Describe the bug**
I noticed a bunch of errors like the following when running:

REMOTE_HOST_PING=no ./osync.sh ... --errors-only --summary --silent
mv: /Volumes/Drobo/.foo/.osync_workdir/state/initiator-tree-current-quicksync_task: set owner/group (was: 501/0): Operation not permitted
mv: /Volumes/Drobo/.foo/.osync_workdir/state/target-tree-current-quicksync_task: set owner/group (was: 501/0): Operation not permitted
mv: /Volumes/Drobo/.foo/.osync_workdir/state/initiator-tree-after-quicksync_task: set owner/group (was: 501/0): Operation not permitted
mv: /Volumes/Drobo/.foo/.osync_workdir/state/target-tree-after-quicksync_task: set owner/group (was: 501/0): Operation not permitted

The permissions on /tmp in OS X are:

$ pwd
/tmp
$ ls -lad
drwxrwxrwt  7 root  wheel  238 Nov  1 18:17 .

The files are being created with group 'wheel'. The mv fails to preserve these permissions.

Perhaps provide a way to set RUN_DIR?

**Comment by deajan** [comment]
Could you try to manually move one of those files from /tmp to  /Volumes/Drobo/.foo/.osync_workdir/state ?
Also, what version of osync are you using ?

**Comment by valankar** [comment]
A manual mv gives the same error. It loses the 'wheel' group ownership once it is moved. The move is successful though.

I'm using:

osync 1.2 2017032101

**Comment by deajan** [comment]
Well, sorry to say, but that's more a system problem than an osync one, and I don't have a Mac to test.
If MacOS works that way, you can indeed change $RUN_DIR to someting in the /Volumes path, but it will probably trigger other issues.

Best way is to find out why even manual move requests change the ownership.
If you can report this back, I can happily fix osync for that particular problem on Mac.

**Comment by valankar** [comment]
The /tmp directory behaves a bit strange on Mac. It is owned by root:wheel. It has the sticky bit, which is expected. But any file created there is inheriting the group owner of wheel. That normally does not happen on other unixes unless the setuid bit is set on the directory.

Found some info here:

https://apple.stackexchange.com/questions/275521/how-does-group-wheel-get-on-my-files

**Comment by deajan** [comment]
From what I've read in the stackexchange above, it's not only the /tmp dir, isn't it ?
Dis you run osync as root ?
What FS does the /Volumes/Drobo mountpoint have ?

**Comment by valankar** [comment]
/Volumes/Drove is UFS:

/dev/disk1s2 on /Volumes/Drobo (hfs, local, nodev, nosuid, journaled, noowners)

The basic issue is that when you create files in /tmp, the group owner of the file gets set to 'wheel'. This is not a group that normal users are part of:

$ groups
staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin 1 _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh

$ id
uid=501(virajalankar) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)

So what happens is, when you 'mv' a file, it is trying the chgrp the file to GID 0, which is wheel:

$ grep wheel /etc/group
wheel:*:0:root

Since normal users are not members of the wheel group, the chgrp will fail. These are the fun things with sticky bit and setuid on directories (latter of which seems implicit on OS X).

**Comment by deajan** [comment]
If this only affects /tmp, is there any safe directory toi use as $RUN_DIR under MacOS ?

**Comment by valankar** [comment]
I found this in 'man mv' on mac:

     As the rename(2) call does not work across file systems, mv uses cp(1) and rm(1) to accomplish the move.  The effect is equivalent
     to:

           rm -f destination_path && \
           cp -pRP source_file destination && \
           rm -rf source_file

Also note that the return value of mv is 0 in this case:

Virajs-Mac-mini:tmp virajalankar$ touch a
Virajs-Mac-mini:tmp virajalankar$ mv a /Volumes/Drobo/
mv: /Volumes/Drobo/a: set owner/group (was: 501/0): Operation not permitted
Virajs-Mac-mini:tmp virajalankar$ echo $?
0

I think /tmp is fine to use. I'm not sure what else could be usable. This is really just a case of annoying errors. I've basically sent stderr to /dev/null running osync on my mac boxes, but realize that's not the best solution.

**Comment by deajan** [comment]
Doesn't `cp -p` try to preserve ownership, thus creating the same problem ?
Can you try this:
```
touch /tmp/file
cp /tmp/file /Volumes/Drobo/file
rm -f /tmp/file
```

If this works, I'll happily create a MacOS test fix for you to try.
Btw, what version of MacOS you're running ? I did previous tests on MacO Sierra and never had that problem.

**Comment by valankar** [comment]
Both 'cp' and 'cp -p' work without errors. So the man page is not even correct.

```
Virajs-Mac-mini:tmp virajalankar$ touch /tmp/file
Virajs-Mac-mini:tmp virajalankar$ cp -p /tmp/file /Volumes/Drobo/file
Virajs-Mac-mini:tmp virajalankar$ rm -f /tmp/file
```

```
Virajs-Mac-mini:tmp virajalankar$ touch /tmp/file
Virajs-Mac-mini:tmp virajalankar$ cp /tmp/file /Volumes/Drobo/file
Virajs-Mac-mini:tmp virajalankar$ rm -f /tmp/file
```

I'm using OS X High Sierra 10.13.6.

**Comment by deajan** [comment]
Working on a fix.
Would you mind trying the macos-fix branch ?

**Comment by valankar** [comment]
Thanks, just tried it. No problems.

**Comment by deajan** [comment]
Do not use it yet, it triggers alot of other deletion related errors. I'll keep you updated.

**Comment by deajan** [comment]
Finally got to merge a better macos fix that also handles symlink problems that came with the initial fixes.
Felel free to reopen the issue if needed.

**Comment by aleixsr** [comment]
Hello, It's happening here again: 

Creating target replica file list [/volume1/NetBackup/VMs/W10.ok/].
mv -f /tmp/osync.treeList.initiator.76400.20220214T113833.N /Volumes/DATA/VMs/W10.ok/.osync_workdir/state/initiator-tree-after-quicksync_task
mv: /Volumes/DATA/VMs/W10.ok/.osync_workdir/state/initiator-tree-after-quicksync_task: set owner/group (was: 501/0): Operation not permitted
mv -f /tmp/osync.treeList.target.76400.20220214T113833.N /Volumes/DATA/VMs/W10.ok/.osync_workdir/state/target-tree-after-quicksync_task
mv: /Volumes/DATA/VMs/W10.ok/.osync_workdir/state/target-tree-after-quicksync_task: set owner/group (was: 501/0): Operation not permitted
Finished synchronization task.

**Comment by deajan** [comment]
If you want some assistance, you really need to post a bit more context.
OS used, osync version used for starters.
