### ISSUE TITLE
Special character handling

### ISSUE THREAD

**Issue by richard-sterling** [deajan/osync#178]
Running osync (current master, aka 1.3 beta 3) against a directory containing filenames with the # character results in errors.

Populate a directory with files containing unusual characters (In this case, `#`)
`/usr/local/bin/osync.sh /etc/osync/storage-storage2_prepress.conf --dry --verbose`

```
TIME: 249 - Could not get file attributes for [/var/storage/prepress/C2/44-300-399/44360/Supplied/send/Icon\#015].
TIME: 850 - Getting file time attributes failed [] on initiator. Stopping execution.
```
Path names have been shortened for legibility

 - OS: Initiator CentOS8 (target is Ubuntu 14.04)
 - Bitness: x64
 - Shell: bash

From the terminal ls reports the name of this file as 'Icon'$'\r' so it's not surprising that osync chokes on it as well.

Obviously the best solution is to not have unusual/difficult to handle/illegal characters in file names, but reality sometimes disagrees (mostly due to OSX clients allowing, and even encouraging these). It appears the script continues after these errors, but as I've been running with --dry it's not clear if these files would be transferred or ignored, or have some other adverse effect.

**Comment by deajan** [comment]
I created a test file "some # file" and cannot reproduce the bug.
Can you please test with latest master ?

Here's my try
```
mkdir t1 t2
touch "t1/some \# file"
touch "t2/some#other file"
touch "t1/#015"
PRESERVE_ACL=true osync.sh --initiator=t1 --target=t2 --summary 
```

**Comment by deajan** [comment]
Any news on this ?

**Comment by richard-sterling** [comment]
I've just redeployed the data and now I can't seem to reproduce. Sorry!

**Comment by deajan** [comment]
Thanks for the answer.
Feel free to reopen if you run into that issue again.
