### ISSUE TITLE
Ping at work is blocked and triggers error.

### ISSUE THREAD

**Issue by GAZ082** [deajan/osync#180]
Hi. At work i tried to sync my computer with my home server and the thing is the ping service is blocked by the sysadmin. I believe this also triggers the CheckConnectivityRemoteHost error.

Can the conn check be disabled? Thanks!

> ExecTasksPidsCheck called by [CheckConnectivityRemoteHost] finished monitoring pid [12265] with exitcode [1].
> TIME: 233 - Cannot ping [xxx.com]. Return code [1].

**Comment by deajan** [comment]
Hi,

You can disable ping tests in the config file.

BR.

**Comment by GAZ082** [comment]
> Hi,
> 
> You can disable ping tests in the config file.
> 
> BR.

Thanks! The sample config file is with the "default" values? Because I tried to use a custom configuration file with just the parameters I use and realized I have to also define others. Wonder I if can just modify the parameters needed and leave the rest as is.

**Comment by deajan** [comment]
Your config file must be complete.
Only a couple of values have defaults, so osync can work without a config file at all.

**Comment by GAZ082** [comment]
Thanks.
