### ISSUE TITLE
Let osync-batch.sh return values depending on results of a job

### ISSUE THREAD

**Issue by Jirixek** [deajan/osync#187]
Hi,

I'm synchronizing my machines with osync-batch.sh. However, there is currently no way to distinguish (other the mail) if a job succeeded after its n tries or not. Is it possible to let osync-batch.sh return value depending on success? Or maybe include option in .conf file to execute a script when the job fails.

Cheers,
Jirixek

**Comment by deajan** [comment]
Hi,

Not sure what you mean. osync-batch returns 1 when one of the sync jobs had errors, and 2 if one of them had warnings.

**Comment by Jirixek** [comment]
Does it really? I can't get it to work. Take a look:
```
Fri 14 Feb 2020 06:15:22 PM CET - Fri 14 Feb 2020 06:15:22 PM CET osync batch run
Fri 14 Feb 2020 06:15:22 PM CET - Sequential run n°1 of osync instances for:
Fri 14 Feb 2020 06:15:22 PM CET - mrdky.conf
Fri 14 Feb 2020 06:15:22 PM CET - home.conf
Fri 14 Feb 2020 06:15:25 PM CET - [91mInstance mrdky.conf failed with exit code [1].[0m
Fri 14 Feb 2020 06:15:28 PM CET - [91mInstance home.conf failed with exit code [1].[0m
Fri 14 Feb 2020 06:15:28 PM CET - Sequential run n°2 of osync instances for:
Fri 14 Feb 2020 06:15:28 PM CET - mrdky.conf
Fri 14 Feb 2020 06:15:28 PM CET - home.conf
Fri 14 Feb 2020 06:15:32 PM CET - [91mInstance mrdky.conf failed with exit code [1].[0m
Fri 14 Feb 2020 06:15:35 PM CET - [91mInstance home.conf failed with exit code [1].[0m
```
```
jirik@BlackJesus ~/.osync $ osync-batch.sh --path=backup/ --max-runs=2
jirik@BlackJesus ~/.osync $ echo $?
0
```

**Comment by deajan** [comment]
Sorry for the late response.
I've tried this and it seems to work for me.
Could you test latest git master for the sake of sanity ?

**Comment by deajan** [comment]
Finally found the issue which didn't happen with the version I tested.
Fixed in master.
