### ISSUE TITLE
ert=/usr/local/bin/osync.sh: line 1690: [: -ne: unary operator expected

### ISSUE THREAD

**Issue by sgiannulli** [deajan/osync#195]
Hello,
testing osync 1.3.0-rc1 on Armbian/Debian 10:
`osync.sh /etc/osync/sync.conf`
give this alert during process:
`ert=/usr/local/bin/osync.sh: line 1690: [: -ne: unary operator expected`

**Comment by deajan** [comment]
Should be fixed in latest master. Thanks.
