### ISSUE TITLE
Q: How it is possible minimize data trasfered on sync ?

### ISSUE THREAD

**Issue by Vladimirek** [deajan/osync#196]
With my setup one sync run take 30MB down and 10MB up network traffic. Nothing is synchronized at all. Is there a config option to minimize this amount of data ? I already have a SSH compression on.
Thanks.

**Comment by deajan** [comment]
Guess you have a big list of files that needs comparaison. By default, osync does not use a lot of network.
Can you give some more details ?

**Comment by Vladimirek** [comment]
Yes exactly. Two devices with tons of files. 
The list .osync_workdir/state/initiator-timestamps-after-sync_test is 24MB / 150.000 lines
But it can be compressed to 1.5MB by tar.gz. That is probably the switch/option/functionality which I looking for.

**Comment by deajan** [comment]
There are only two options for data compression which are SSH_COMPRESSION and RSYNC_COMPRESSION.
While RSYNC_COMPRESSION is for sending files only, SSH_COMPRESSION will be less good than gzip since it handles a stream only, and has to keep a good balance between speed and compression.

I don't currently know how to imrpove SSH_COMPRESSION.

**Comment by Vladimirek** [comment]
I try more investigation on this, and when i create a huge test directory tree with [1], the compression ssh or rsync does not affect the transfer size.

SSH_COMPRESSION=true, RSYNC_COMPRESS=true  In/Out: 51.9 / 145.1 MB
SSH_COMPRESSION=false, RSYNC_COMPRESS=true In/Out: 51.9 / 145.1 MB
SSH_COMPRESSION=false, RSYNC_COMPRESS=false In/Out: 52.4 / 145.1 MB
(counting on remote side)

When I googled around i found that it is possible to speed up the rsync by handle only newer than something by --files-from directive [2]. 
Or replace by generic "find . -newer /reference/file" [3] point to last osync file list for example.
I know that this can miss some file, but I can live with it by run full sync time by time.

For testing I do a dirty modify line 4039 to:
...$exclude_list_target --files-from=<(find \"$sourceDir\"/./ -mmin -7 -print0) / $REMOTE_USER@$...
It is working as expected, but I am not a 'shell friend' so i am lost how to modify remote->local part.

For me it is closed. 
It can be feature request: Check only files which changed from last sync run / or last x days.

[1] https://pastebin.com/BACpLkFK
[2] https://superuser.com/a/297343
[3] https://unix.stackexchange.com/a/147665

Thanks for your time.

-vladimir-
