### ISSUE TITLE
systemd service is created with --on-changes-target

### ISSUE THREAD

**Issue by Artiom-M** [deajan/osync#199]
Latest beta installed with installer has created a systemd service with `--on-changes-target` that actually stops syncronization in my config.

**Comment by deajan** [comment]
Sorry for the late reply, but this issue report lacks any contextual information to help here.
Please be more precise, include file you're talking about, logs, config file and osync version.

**Comment by Artiom-M** [comment]
PROGRAM_VERSION=1.3.0-beta3
PROGRAM_BUILD=2019052201
I have master and passive slave, so on changes on master it does sync, and every 2 hours (MAX_WAIT=7200)  is force check the target.

so in this file:

*/usr/lib/systemd/system/osync-srv@.service*
ExecStart actually has had --on-changes-target option and this is on my master host prevents any synchronisation to happen.
When changed to `on-changes` it works as expected.

```
[Unit]
Description=osync - Target helper service
After=time-sync.target local-fs.target network-online.target
Requires=time-sync.target local-fs.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/osync.sh /etc/osync/%i --on-changes --errors-only
SuccessExitStatus=0 2

[Install]
WantedBy=multi-user.target
```

There is nothing special on the log, just nothing happens.

**Comment by deajan** [comment]
Thanks, already fixed in https://github.com/deajan/osync/commit/572a05590173009340bdf155d6b5cb22aa979b2f#diff-e0ca2884837a77df93f98f219cb2339f
