### ISSUE TITLE
Permanent warning in the log about conflicts, but 0 conflictual files...

### ISSUE THREAD

**Issue by Artiom-M** [deajan/osync#200]
TIME: 677 - File conflicts: INITIATOR << >> TARGET
TIME: 677 - There are **0** conflictual files.
TIME: 679 - (WARN):osync finished with warnings.

**Comment by deajan** [comment]
Can you post the full log, version and config file ?
I just audited my code, and listing file conflicts shouldn't trigger a warning.

**Comment by deajan** [comment]
I indeed found that logging "0 conflictual files" is overkill and simplified the logs, but this shoudln't bring any functional modifications upon your issue.
Can you retry with latest master ?

**Comment by Artiom-M** [comment]
Can I just take osync.sh from master or I need other files?

**Comment by deajan** [comment]
Just rebuilt the target so, yes, you can, unless you use earlier versions of the config file (pre v1.3).

**Comment by Artiom-M** [comment]
Tried new script from master and it works.
