### ISSUE TITLE
Arch Linux, Manjaro: Cannot get value for [VERSION] in config file [/etc/os-release].

### ISSUE THREAD

**Issue by sfrieske** [deajan/osync#205]
On Arch Linux and Manjaro an error is printed:
`Cannot get value for [VERSION] in config file [/etc/os-release].`

This is correct because Arch based distos don't have a notion of a version.
osync should silently skip the VERSION information if it is not in /etc/os-release. 

**To Reproduce**
**Steps to reproduce the behavior:**
run osync.sh with usual parameters on Arch like linux.

**Expected behavior**
Error not happening/not displayed.

**Comment by deajan** [comment]
Dupes of #134 and #190
