### ISSUE TITLE
Updating Owners/Groups to root:root With Preserve Options Set to `no`

### ISSUE THREAD

**Issue by TheRealDwright** [deajan/osync#212]
**Describe the bug**
When syncing from an initiator (mounted using SSHFS) to a target (CIFS share mounted to RHEL7) and setting all the PRESERVE** options to `no` and setting the rsync args to `--modify-window=2 --omit-dir-times` I am seeing that regardless of of what order I run the command, osync will change permissions to root:root every sync.

**To Reproduce**
1. Setup osync with the following config file / the following parameters
```
RSYNC_OPTIONAL_ARGS="--modify-window=2 --omit-dir-times"
PRESERVE_PERMISSIONS=no
PRESERVE_OWNER=no
PRESERVE_GROUP=no
PRESERVE_EXECUTABILITY=no
PRESERVE_ACL=no
PRESERVE_XATTR=no
COPY_SYMLINKS=no
KEEP_DIRLINKS=no
PRESERVE_HARDLINKS=no
CHECKSUM=no
```
Note: this was performed with an initiator/target as folows:
**Initiator**: sshfs
**Target**: cifs share

2. Run osync with following parameters
/usr/bin/osync.sh /etc/osync/custom.config --initiator="/mnt/sshfs" --target="/mnt/cifs"

3. Result
All permissions on /mnt/sshfs are set as owner: root group: root which is reflected in the logs with multiple entries to the effect of: `set "/sshfs/test.txt" owner 0 group 0 [postauth]`

**Expected behavior**
I expect that with the above options enabled, osync would not interfere with permissions on neither the initiator or the target.

**Logs**
Please send logs of what happens.
Also, you might run osync with _DEBUG=yes environment variable to have more verbose debug logs.

```
_DEBUG=yes /usr/bin/osync.sh /etc/osync/custom.config --initiator="/mnt/sshfs" --target="/mnt/cifs"
TIME: 0 - Script begin, logging to [/var/log/osync.quicksync_task.log].
TIME: 0 - Local OS: [Linux 3.10.0-1127.19.1.el7.x86_64 x86_64 x86_64 GNU/Linux].
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Wed Sep 23 17:58:59 AEST 2020 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [quicksync_task] launched as root@osync (PID 2245)
TIME: 0 - Checking minimum disk space in local replica [/mnt/sshfs/].
TIME: 0 - Checking minimum disk space in local replica [/mnt/cifs/].
TIME: 0 - Locked local target replica in [/mnt/cifs/.osync_workdir/lock].
TIME: 1 - Locked local initiator replica in [/mnt/sshfs/.osync_workdir/lock].
TIME: 1 - Starting synchronization task.
TIME: 1 - Trying to resume aborted execution on 2020-09-23 17:58:55.000000000 +1000 at task [replica-tree] for initiator. [0] previous tries.
TIME: 1 - Trying to resume aborted execution on 2020-09-23 17:58:56.000000000 +1000 as task [deleted-list] for target. [0] previous tries.
TIME: 1 - Creating initiator replica file list [/mnt/sshfs/].
TIME: 1 - RSYNC_CMD: /bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file  -p -o -g --executability  --exclude ".osync_workdir"   --list-only "/mnt/sshfs/" 2> "/tmp/osync.treeList.initiator.error.2245.20200923T175859.772299282" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.initiator.2245.20200923T175859.772299282"
TIME: 5 - Creating initiator replica deleted file list.
TIME: 5 - Creating target replica deleted file list.
TIME: 5 - Launching command [comm -23 "/mnt/sshfs/.osync_workdir/state/initiator-tree-after-quicksync_task" "/mnt/sshfs/.osync_workdir/state/initiator-tree-current-quicksync_task" > "/mnt/sshfs/.osync_workdir/state/initiator-deleted-list-quicksync_task"].
TIME: 5 - Launching command [comm -23 "/mnt/sshfs/.osync_workdir/state/target-tree-after-quicksync_task" "/mnt/sshfs/.osync_workdir/state/target-tree-current-quicksync_task" > "/mnt/sshfs/.osync_workdir/state/target-deleted-list-quicksync_task"].
TIME: 6 - Updating target replica.
TIME: 6 - RSYNC_CMD: /bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file   -p -o -g --executability  -u -i --backup --backup-dir=".osync_workdir/backup" --exclude ".osync_workdir"   --exclude-from="/mnt/sshfs/.osync_workdir/state/initiator-deleted-list-quicksync_task" --exclude-from="/mnt/sshfs/.osync_workdir/state/target-deleted-list-quicksync_task" "/mnt/sshfs/" "/mnt/cifs/" >> /tmp/osync.update.target.2245.20200923T175859.772299282 2>&1
TIME: 11 - List:
.d...pog... staff/joebloggs/
.d...p.g... staff/joebloggs/.admin/
.f...p..... staff/joebloggs/.admin/.protected
TIME: 11 - Updating target replica succeded.
TIME: 11 - Updating initiator replica.
TIME: 11 - RSYNC_CMD: /bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file   -p -o -g --executability  -u -i --backup --backup-dir=".osync_workdir/backup" --exclude ".osync_workdir"   --exclude-from="/mnt/sshfs/.osync_workdir/state/target-deleted-list-quicksync_task" --exclude-from="/mnt/sshfs/.osync_workdir/state/initiator-deleted-list-quicksync_task" "/mnt/cifs/" "/mnt/sshfs/" >> /tmp/osync.update.initiator.2245.20200923T175859.772299282 2>&1
TIME: 33 - List:
.d...pog... staff/joebloggs/
.d...p.g... staff/joebloggs/.admin/
.f...p..... staff/joebloggs/.admin/.protected
TIME: 33 - Updating initiator replica succeded.
TIME: 33 - Propagating deletions to initiator replica.
TIME: 33 - Propagating deletions to target replica.
TIME: 33 - Creating initiator replica file list [/mnt/sshfs/].
TIME: 33 - RSYNC_CMD: /bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file  -p -o -g --executability  --exclude ".osync_workdir"   --list-only "/mnt/sshfs/" 2> "/tmp/osync.treeList.initiator.error.2245.20200923T175859.772299282" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.initiator.2245.20200923T175859.772299282"
TIME: 33 - Creating target replica file list [/mnt/cifs/].
TIME: 33 - RSYNC_CMD: /bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 --no-whole-file  -p -o -g --executability  --exclude ".osync_workdir"   --list-only "/mnt/cifs/" 2> "/tmp/osync.treeList.target.error.2245.20200923T175859.772299282" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.target.2245.20200923T175859.772299282"
TIME: 45 - Finished synchronization task.
TIME: 45 - Running conflict backup cleanup.
TIME: 45 - Removing files older than 30 days on target replica for conflict backup deletion.
TIME: 45 - Command output:

TIME: 45 - File cleanup complete on target replica.
TIME: 45 - The initiator replica dir [/mnt/sshfs/.osync_workdir/backup] does not exist. Skipping cleaning of old files.
TIME: 45 - Command output:

TIME: 45 - Directory cleanup complete on target replica.
TIME: 45 - Running soft deletion cleanup.
TIME: 45 - Removing files older than 30 days on initiator replica for softdelete deletion.
TIME: 45 - Removing files older than 30 days on target replica for softdelete deletion.
TIME: 45 - Command output:

TIME: 45 - File cleanup complete on target replica.
TIME: 45 - Command output:

TIME: 45 - File cleanup complete on initiator replica.
TIME: 45 - Command output:

TIME: 45 - Directory cleanup complete on initiator replica.
TIME: 45 - Command output:

TIME: 45 - Directory cleanup complete on target replica.
TIME: 45 - Removed local target replica lock.
TIME: 45 - Removed local initiator replica lock.
TIME: 45 - osync finished.
```

**Desktop (please complete the following information):**
 - OS: RHEL7 (3.10.0-1127.19.1.el7.x86_64)
 - Bitness x86_64
 - Shell GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Additional context**
It is worth noting that the sshfs is a SFTP server running a chroot'ed file system. If I mount the sshfs using a service user on the sftp, osync is unable to create the .osync_workdir and this causes other issues. To try and avoid challenges with permissions, I mounted the dir using sshfs with a root user using a private key. This is what resulted in osync being very harsh with setting permissions on the initiator.

I've also tried with a stable osync 1.2 2017032101 and the version of the codebase in this repo at the time of writing this issue.

**Comment by deajan** [comment]
Sorry to ask, but I'm not really sure to understand.
You disabled `PRESERVE_OWNER`, so instead of writing the file as with it's original owner, osync will write the files as current user, which in your logs is root, which is the expected behavior.

Also, keep in mind that eveything that applies to rsync applies to osync.
You can just try to `rsync -rltptgoDEui /source /mnt/sshfs /mnt/cifs` to see whether the results you expect are achievable in your system.
`-o` is preserve owner, `-g` is preserve group, which have eponymous settings in osync.

Lastly, since you use sshfs which is a FUSE hosted FS, you should check the following https://serverfault.com/questions/755753/preserve-ownership-with-rsync-without-root

Hope this helps.

**Comment by TheRealDwright** [comment]
Thanks so much for the quick response @deajan, I'll have a look at options and test today. Just to clarify, are you suggesting if I want to maintain permissions on the initiator, I should be using default configuration with osync?

**Comment by TheRealDwright** [comment]
And one more question if I may, because in testing using your example rysnc command, to be really concise is.

1. Copy from initiator > target = works as expected, permissions are maintained
2. Copy from target > initiator = overrides permissions on the initiator for all files and directories

The second step is what I'm trying to avoid, how best could this be achieved using Osync if at all possible? 

In testing with none of the preserve options enabled, I still encountered the issue that all permissions for files and folders were reset to root:root on the initiator (sshfs)

I will continue debugging on my side.

**Comment by TheRealDwright** [comment]
Hi @deajan,

Feel free to close this, however for those interested my issue was not related to osync, but rather a problem in where mounting a CIFS file system to Linux using vers=3.0 does not support the unix toolset. After mounting the share as an NFS volume instead of CIFS we saw permissions being correctly copied between initiator and target.

Thanks

**Comment by deajan** [comment]
Thanks for reporting back ;)
