### ISSUE TITLE
Does it work for large number of files?

### ISSUE THREAD

**Issue by rameshar16** [deajan/osync#213]
Hi @deajan,

I am planning to use osync for the bidirectional real-time sync purpose. I have the below questions. Kindly help me on this.

1. Does it support a larger number of files. (In my case, the files count is around 1 million files on both source and target dir)
2. Does it support a large number of files (In my case each file size is around 1 GB)?
3, Does it take time to start the process of the files if we restart the service. ( I am using a tool called Mirror, if we restart the service, it is taking time to calculate the files on both source and target and after some time (30 min to 60min) it started to sync the files.

Thanks and Regards,
Ramesh AR

**Comment by deajan** [comment]
Hello,

Sorry for the late answer.
1. So far I have tested with about 750k files, so I guess 1 million files is no problem ;)
2. The size of the file is not relevant (rsync delta algorithm used).
3. osync is stateful, meaning it syncs whenever it's called via cron or so. Using your number of files, indeed the service which looks for file changes will probably not work well (too many inodes) unless you increase the open inodes value in kernel (see inotifywait limitations).

As a reminder, osync is supposed to run like every night or so for big transfers over bad links, it's not intended to be realtime.

**Comment by rameshar16** [comment]
Hi @deajan,

Thank you for the details.

Thanks and Regards,
Ramesh AR
