### ISSUE TITLE
awk: cmd. line:1: Unmatched ( or \(

### ISSUE THREAD

**Issue by Artiom-M** [deajan/osync#214]
I am getting those errors that blocs the replication

TIME: 0 - Wed Oct  7 15:34:42 EDT 2020 - osync 1.3.0-rc1 script begin.
awk: cmd. line:1: (FILENAME=- FNR=52) fatal: Unmatched ( or \(: /^ScanSnap/20201002_f) $Mi(A w_inlj_.jpg//
TIME: 4 - (CRITICAL):Could not prepare initiator deletion list.

It looks like it have encountered a weird file name with () in it:

`'20201002_f) $Mi(A w_inlj_.jpg'`

**Comment by deajan** [comment]
Unless the filename you posted has been obtained via `ls -b`, would you mind making an `ls -alb` of the directory containing the offending file, and post the relevant line ?

**Comment by Artiom-M** [comment]
This is copy/paste of what I can see with `ls -alb`:
```
166252 Oct  2 09:58 20201002_f)\ $Mi(A\ w_inlj_.jpg
```

**Comment by Artiom-M** [comment]
It really does not like **(**.
These names are automatically created by a scanner software and there is no way to prevent it to happen

**Comment by deajan** [comment]
I am unable to reproduce that error.
Is there a chance I could get monitored ssh access to the box for a couple of minutes ?

**Comment by Artiom-M** [comment]
I haven't seen this again since that time. So I think this can be closed as for now.
