### ISSUE TITLE
Error with configuration file at CREATE_DIRS

### ISSUE THREAD

**Issue by renyuneyun** [deajan/osync#216]
I copied the configuration file example from the repository, and modified it according to my needs.
However, when executing osync, it raises an error and seemed to not proceed.
The error is:

    TIME: 0 - Bogus CREATE_DIRS value [true] defined in config file. Correct your config file or update it using the update script if using and old version.
    TIME: 0 - osync finished with errors.

In the corresponding section, I wrote:
```
CREATE_DIRS=true
```
which is the same as the one given in the example.

I looked at the source code, and found that part reads:
```
test="if [ \"\$$i\" != true ] && [ \"\$$i\" != false ];
```

Could this be due to the direct usage of `true` and `false` (value) here, as opposed to a string?

**Comment by deajan** [comment]
I'm pretty sure you've used a config file from current master (v1.3) with osync v1.2. Can you confirm ?

**Comment by renyuneyun** [comment]
Thanks very much. You are absolutely right....

It appears my previous comment didn't send out correctly... Sorry for the long delay.
