### ISSUE TITLE
Cannot move /var/lib/samba/sysvol/ramls/folder2 to deletion directory

### ISSUE THREAD

**Issue by dcmwai** [deajan/osync#22]
Hello there,

It seem that osync will have issue if the folder remove 
/var/lib/samba/sysvol/ramls/folder2

is already exist on the backup directory before (possible because of it was created and remove later)

Thank You

**Comment by deajan** [comment]
Hello,

This bug report isn't clear enough for me to get your problem.
Could you please explain in detail what your problem is ? Also run osync with --verbose parameter.
Do you have perhaps an error message that comes with osync ?

Without actual information, i cannot look further into this issue.

**Comment by dcmwai** [comment]
This is the log and also some configuration
I think the problem is on the soft delete

As I've "/var/lib/samba/sysvol/ramls/folder2" before (with some files)
And I deleted that on host 1 after the 1st sync.

But I've recreated the same files and folder on slave for testing.
sync one and remove it on host 2 and this time this sync will fail because the same folder is present on the deleted (osync folder)

I think we should have some number if there is conflict on folder name or files name.

_Configuration
CONFLICT_BACKUP=yes
CONFLICT_BACKUP_MULTIPLE=no
CONFLICT_BACKUP_DAYS=30
CONFLICT_PREVALANCE=master
SOFT_DELETE=yes
SOFT_DELETE_DAYS=30

_Log
TIME: 1 - -------------------------------------------------------------
TIME: 1 -  Wed Jun 24 03:05:02 MYT 2015 - Osync 1.00pre script begin.
TIME: 1 - -------------------------------------------------------------
TIME: 1 - Sync task [samba_sysvol] launched as users1@srv01 (PID 22412)
TIME: 2 - Checking minimum disk space on master and slave.
TIME: 4 - Checking for replica locks.
TIME: 5 - Locked master replica.
TIME: 5 - Locked remote slave replica.
TIME: 5 - Starting synchronization task.
TIME: 6 - Creating master replica file list [/var/lib/samba/sysvol/].
TIME: 7 - Creating slave replica file list [/var/lib/samba/sysvol/].
TIME: 8 - Creating master replica deleted file list.
TIME: 8 - Creating slave replica deleted file list.
TIME: 8 - Updating slave replica.
TIME: 9 - Updating slave replica succeded.
TIME: 9 - Updating master replica.
TIME: 11 - Updating master replica succeded.
TIME: 11 - Propagating deletions to slave replica.
TIME: 17 - Propagating deletions to master replica.
TIME: 17 - Cannot move /var/lib/samba/sysvol/ramls/folder2 to deletion directory.
TIME: 17 - Creating master replica file list [/var/lib/samba/sysvol/].
TIME: 17 - Creating slave replica file list [/var/lib/samba/sysvol/].
TIME: 18 - Finished synchronization task.
TIME: 18 - Running conflict backup cleanup.
TIME: 18 - Removing files older than 30 days on master replica.
TIME: 18 - Cleanup complete on master replica.
TIME: 19 - Removing files older than 30 days on slave replica.
TIME: 19 - Cleanup complete on slave replica.
TIME: 19 - Running soft deletion cleanup.
TIME: 19 - Removing files older than 30 days on master replica.
TIME: 19 - Cleanup complete on master replica.
TIME: 20 - Removing files older than 30 days on slave replica.
TIME: 20 - Cleanup complete on slave replica.
TIME: 21 - Removed slave replica lock.
TIME: 21 - Removed master replica lock.
TIME: 21 - Osync finished.

**Comment by deajan** [comment]
Could you please grab the following osync.sh file and try again ?
https://github.com/deajan/osync/raw/fix%2322/osync.sh

**Comment by dcmwai** [comment]
It seem that it is same

TIME: 1 - -------------------------------------------------------------
TIME: 1 -  Wed Jun 24 20:21:42 MYT 2015 - Osync 1.00pre script begin.
TIME: 1 - -------------------------------------------------------------
TIME: 1 - Sync task [sysvol2] launched as users@srv01 (PID 35233)
TIME: 2 - Checking minimum disk space on master and slave.
TIME: 4 - Checking for replica locks.
TIME: 5 - Locked master replica.
TIME: 6 - Locked remote slave replica.
TIME: 6 - Starting synchronization task.
TIME: 16 - Creating master replica file list [/var/lib/samba/sysvol2/].
TIME: 17 - Creating slave replica file list [/var/lib/samba/sysvol2/].
TIME: 18 - Creating master replica deleted file list.
TIME: 18 - Creating slave replica deleted file list.
TIME: 18 - Updating slave replica.
TIME: 19 - List:
.d..t...... ramls/
TIME: 19 - Updating slave replica succeded.
TIME: 19 - Updating master replica.
TIME: 21 - List:

TIME: 21 - Updating master replica succeded.
TIME: 21 - Propagating deletions to slave replica.
TIME: 26 - Remote:

TIME: 26 - Propagating deletions to master replica.
TIME: 26 - Soft deleting /var/lib/samba/sysvol2/ramls/folder1
mv: cannot move '/var/lib/samba/sysvol2/ramls/folder1' to '/var/lib/samba/sysvol2/.osync_workdir/deleted/folder1': Directory not empty
TIME: 26 - Cannot move /var/lib/samba/sysvol2/ramls/folder1 to deletion directory.
TIME: 26 - Soft deleting /var/lib/samba/sysvol2/ramls/folder2
mv: cannot move '/var/lib/samba/sysvol2/kl01.amtb-m.org.my/folder2' to '/var/lib/samba/sysvol2/.osync_workdir/deleted/folder2': Directory not empty
TIME: 26 - Cannot move /var/lib/samba/sysvol2/ramls/folder2 to deletion directory.
TIME: 26 - Creating master replica file list [/var/lib/samba/sysvol2/].
TIME: 27 - Creating slave replica file list [/var/lib/samba/sysvol2/].
TIME: 28 - Finished synchronization task.
TIME: 28 - Running conflict backup cleanup.
TIME: 28 - Removing files older than 30 days on master replica.
TIME: 28 - Command output:

TIME: 28 - Command output:

TIME: 28 - Cleanup complete on master replica.
TIME: 29 - Removing files older than 30 days on slave replica.
TIME: 29 - Command output:

TIME: 29 - Cleanup complete on slave replica.
TIME: 29 - Running soft deletion cleanup.
TIME: 29 - Removing files older than 30 days on master replica.
TIME: 29 - Command output:

TIME: 29 - Command output:

TIME: 29 - Cleanup complete on master replica.
TIME: 30 - Removing files older than 30 days on slave replica.
TIME: 30 - Command output:

TIME: 31 - Cleanup complete on slave replica.
TIME: 32 - Removed slave replica lock.
TIME: 32 - Removed master replica lock.
TIME: 32 - Osync finished.

**Comment by deajan** [comment]
Okay, i've made some tests here with folder moving and i dont see any problems.
To analyse further, please tell me what OS you're using on both master and slave.

Also, please give me the content of the file "testrun" that you get by running:
```
DEBUG=YES bash -x /path/to/osync.sh /your/conf/file
```
And ad least the output of
```
find /path/to/master/replica/.osync_workdir/deleted
find /path/to/slave/replica/.osync_workdir/deleted
```

**Comment by dcmwai** [comment]
This is the debug log and also the 2 result
https://gist.github.com/dcmwai/1b14f7ef1037c30cc1d9

I'm using it for bi-directional sync for the the sysvol only for AD DC.(as DFS-R is not yet implemented)
https://wiki.samba.org/index.php/SysVol_Bidirectional_Replication
I'll replace that to osync later (not today, tired now)

Just to ask you another question would this also support multi master/slave?
As sometime you have 3 DC...
Things get very complicated than...

**Comment by deajan** [comment]
Thank you for the debug, made it way easier to understand what the problem was. The latest fix#22 build should be ok.
Your sysvol wiki is great, thanks for mentionning osync :)
I'm actually feeling quite confident to release v1.00 (the project syncs production systems since 2 years now). I have to merge the latest PR's and update a bit of documentation, i'll do that these weeks, and have a site release.

As for the multi master/slave support, for now you have to setup one master with multiple slaves, this works without problems, except that you have to trigger cron jobs like the following to be sure that DC2 gets synced to DC3.
DC1 <> DC2
DC1 <> DC3
DC1 <> DC2

Osync also works in file monitor daemon mode (only on master yet).
My plan is to make a multimaster daemon where every server holds a ssh key for it's remote replicas, and on every file change a sync is triggered, using the existing lock mecanism to tell remote replicas to wait until the last sync is terminated.

Mail me (check my mail on my site) if you want to keep in touch about this.

**Comment by dcmwai** [comment]
Strange enough.

it is still not fix.

https://gist.github.com/dcmwai/1b14f7ef1037c30cc1d9

Isn't it better if you move it with version?
Like #[Numbre of copy).foldername or files name
when the files/folder present?

Thank you :)

**Comment by deajan** [comment]
Adding versionning can be a solution, but this may grow the deletion folder to very big sizes depending on the setup.
As i read your gist, i realised you did use the master version and not the hotfix branch.
Can you please test again with the following version ?
https://raw.githubusercontent.com/deajan/osync/fix%2322/osync.sh

**Comment by dcmwai** [comment]
The gist should have 2 debug files. 
One for v1 branch 
And one for version 22

Please check again.

**Comment by deajan** [comment]
My bad, TLDR :)
I now have a better idea of what's going on. Expect a fix this weekend so i have time to fully cover the issue.

**Comment by dcmwai** [comment]
Thank you in advance :+1:

**Comment by deajan** [comment]
I just pushed a new hotfix to branch fix#22. This should definitly work.
Part of the problem was that soft deletion didn't keep the full path of the deleted file, which is a major bug i figured thanks to your issue, so my previous fix didn't work.
Can you test this branch ?

**Comment by dcmwai** [comment]
Fixed ;)

**Comment by dcmwai** [comment]
Oh by the way,
You can put gentoo in the compatible list...

Although it might meant nothing for the gentoo users.

**Comment by deajan** [comment]
Compatible, probably anything that can run bash.
Fully tested, that's what's important to me.
