### ISSUE TITLE
Batch synchronization tasks always fail the first time

### ISSUE THREAD

**Issue by feeyman** [deajan/osync#221]
**_Hello Mr Deajan；
I'm very happy to use this synchronization tool. Thank you. But recently, I found that when processing tasks in batch, the first time always fails. If it is convenient for you, can you test it? I use the Kirin system._**

first：
![image](https://user-images.githubusercontent.com/24524775/99646705-c93d7180-2a8b-11eb-8bae-790546a0e98b.png)

second：
![image](https://user-images.githubusercontent.com/24524775/99646722-cd698f00-2a8b-11eb-94c2-a5a04711768b.png)

**Comment by deajan** [comment]
I have no clue what you're reporting here. There's no error message in your screen, and honestly, without any context, that's not helpful at all.
Please use the bug reporting template, and provide the requested infos.

**Comment by feeyman** [comment]
.
