### ISSUE TITLE
first sync wants to xfer files already manually rsync'd

### ISSUE THREAD

**Issue by senorsmile** [deajan/osync#225]
**Describe the bug**
A first sync using osync wants to transfer (most of?  all of?) the files, even though they were just manually synced from the remote to the local machine. 

**To Reproduce**
0. local machine does NOT yet have the files, only a newly created folder to sync to
1. rsync -avzP user@remote:/remote_path/ /local/path/
2. osync.sh --summary --dry --initiator=/local/path --target="ssh://user@remote/remote_path
3. osync wants to sync lots of files from the local to the remote, even they mtime and all other attrs match

**Expected behavior**
osync has nothing to sync. 

** Deviated behavior**
osync should not want to sync anything, but for my large set of files (which have already been manually rsync'd), it wants to transfer them all again but in the opposite direction.  This is bad because it took over 12 hours to do the initial transfer (lots of large files!).  

**Logs**
https://gist.github.com/senorsmile/37af3736e3d3b9bff4b3cbb1d222c719

**Environment (please complete the following information):**
 - Full osync version (including build) : osync 1.2 2017032101
 - OS: manjaro
 - Bitness: x64
 - Shell: bash

**Comment by deajan** [comment]
I'll need a bit more info. What are the filesystems of both initiator and target paths ?
Are both machines synced with NTP ?

Can you make a test with latest osync master ? It's been 4 years of developpment since v1.2.

**Comment by senorsmile** [comment]
both ext4. 
They are both ntp synced (I had the same thought).  I stopped ntpd and manually synced with ntpd -qg just to make sure. 

I had pulled down osync from the AUR.  I'll uninstall and try from git.

**Comment by senorsmile** [comment]
There were a couple of issues with what I was passing it that weren't apparent in the old version but were immediately apparent in the newest version
`RSYNC_OPTIONAL_ARGS="-s"`

and a bad path which was causing it to want to do a full sync to a new folder on the remote side.

**Comment by deajan** [comment]
Thanks for the update.
