### ISSUE TITLE
ping command fails from crontab on macos

### ISSUE THREAD

**Issue by gasagna** [deajan/osync#232]
Hi, 

this is great software, thanks for developing and maintaining it!

I am having an issue (not blocking, though) with running osync.sh from crontab on a macOS using  a config file

All is fine if i run it from the command line

```
davide@**** - local$: osync.sh sync.conf
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Tue Jul 27 21:34:12 BST 2021 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [quicksync_task] launched as davide@*******(PID 13927)
TIME: 1 - Disabling compression skips on synchronization on [MacOSX] due to lack of support.
TIME: 1 - Checking minimum disk space in local replica [**********].
TIME: 0 - Checking minimum disk space in remote replica [***********].
TIME: 4 - Starting synchronization task.
```

but here is the log file when run through crontab

```
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Tue Jul 27 21:25:00 BST 2021 - osync 1.2 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [quicksync_task] launched as davide@******* (PID 11503)
TIME: 1 - Disabling compression skips on synchronization on [MacOSX] due to lack of support.
TIME: 1 - Checking minimum disk space in local replica [***************].
TIME: 1 - Cannot ping 3rd party host [www.kernel.org]. Return code [127].
TIME: 1 - Cannot ping 3rd party host [www.google.com]. Return code [127].
TIME: 1 - (WARN):No remote 3rd party host responded to ping. No internet ?
```

Note that it fails to ping the remote server. I have checked that I can ping the remote server from the terminal, and that ping is in my `PATH`., but somehow `osync.sh` cannot find the ping command. The return code is 127, which is the default return code returned by `/bin/sh` when the given command is not found within your PATH system variable and it is not a built-in shell command (see [here](https://stackoverflow.com/questions/1763156/127-return-code-from).

Thanks

**Comment by gasagna** [comment]
This is not really an issue with osync, but it's an issue with `cron` not running in the same environment as a normal user (see [here](https://unix.stackexchange.com/questions/384713/script-in-cron-cannot-find-command)). Closing.

**Comment by deajan** [comment]
Thanks for reporting back.
