### ISSUE TITLE
v1.3?

### ISSUE THREAD

**Issue by axkibe** [deajan/osync#243]
Any ETA on v1.3?

I'm using 1.3.0-prerc1 for 2.5 years now (because I wanted ssh ControlMaster).. on my side without issues, except the one case the sync failed due to harddrive full, I couldn't restore it properly and had to remove my local sync directory to pull it again..

Not a biggie, just wondered since I'm using a git snapshot for years now..

PS: But happy user all around..

**Comment by deajan** [comment]
I'm really sorry, the delays have been horrible I know.
You can safely update to latest git master, which alot of people use in production for some time now.
I just need to get time to test on **every** supported platform (especially MacOS which I don't own and have some problems getting virtual machines running).

Once tests are validated everywhere, the current git master will become v1.3 stable.
If you have a working MacOS VM, I would be thrilled.

**Comment by waynetheisinger** [comment]
HI @deajan I'm interested in the Helper Service for master-master daemon mode, I'm interested that you say that the master branch is fairly stable and might give it a go - is there documentation done for this part of 1.3?

**Comment by osiktech** [comment]
@deajan I could provide you with macOS VM.

**Comment by deajan** [comment]
For what it's worth, I've release v1.3.
Includes github action tests for Linux, Windows and macOS.
