### ISSUE TITLE
uninstaller needed

### ISSUE THREAD

**Issue by bcrowell** [deajan/osync#245]
Thanks for creating osync and making it available as free software!

I gave it a test drive, and although it seems nice, it didn't quite fit my own use case. I wanted to uninstall it, but there didn't seem to be any uninstall script. I would suggest adding one. What I guessed was the following:

rm -Rf /etc/osync
rm -f /usr/local/bin/osync.sh /usr/local/bin/osync-batch.sh /usr/local/bin/ssh_filter.sh /lib/systemd/system/osync-srv@.service

**Comment by deajan** [comment]
Thanks for the report, but osync already has an uninstaller script.
Just run `install.sh --remove`.

Feel free to reopen this issue if needed.
