### ISSUE TITLE
Get rid of "blob data" events in log.

### ISSUE THREAD

**Issue by Turranius** [deajan/osync#249]
Me again. I'm still running 1.2 but is there any way to get rid of the "blob data" events when running, for example, journalctl -f

Its the same when running in daemon mode as in crontab. It gets a bit spammy.

Nov 12 16:10:01 localhost CROND[509141]: (root) CMDOUT (TIME: 0 - -------------------------------------------------------------)
Nov 12 16:10:01 localhost CROND[509141]: (root) CMDOUT (TIME: 0 - Sat Nov 12 16:10:01 CET 2022 - osync 1.2 script begin.)
Nov 12 16:10:01 localhost CROND[509141]: (root) CMDOUT (TIME: 0 - -------------------------------------------------------------)
Nov 12 16:10:01 localhost CROND[509141]: (root) CMDOUT (TIME: 0 - Sync task [ftp_no_site] launched as syncuser@*censored* (PID 509150))
Nov 12 16:10:02 localhost CROND[509141]: (root) CMDOUT (TIME: 1 - Checking minimum disk space in local replica [/glftpd/].)
Nov 12 16:10:03 localhost CROND[509141]: [491B blob data]
Nov 12 16:10:04 localhost CROND[509141]: [464B blob data]
Nov 12 16:10:04 localhost CROND[509141]: [86B blob data]
Nov 12 16:10:04 localhost CROND[509141]: (root) CMDOUT (TIME: 3 - Creating target replica file list [/glftpd/].)
Nov 12 16:10:06 localhost CROND[509141]: [491B blob data]
Nov 12 16:10:06 localhost CROND[509141]: [80B blob data]
Nov 12 16:10:06 localhost CROND[509141]: [74B blob data]
Nov 12 16:10:07 localhost CROND[509141]: [491B blob data]
Nov 12 16:10:07 localhost CROND[509141]: [77B blob data]
Nov 12 16:10:08 localhost CROND[509141]: [506B blob data]
Nov 12 16:10:09 localhost CROND[509141]: [81B blob data]
Nov 12 16:10:09 localhost CROND[509141]: [78B blob data]
Nov 12 16:10:09 localhost CROND[509141]: [218B blob data]
Nov 12 16:10:09 localhost CROND[509141]: (root) CMDOUT (TIME: 8 - Creating target replica file list [/glftpd/].)
Nov 12 16:10:11 localhost CROND[509141]: [477B blob data]
Nov 12 16:10:11 localhost CROND[509141]: (root) CMDOUT (TIME: 10 - Running conflict backup cleanup.)
Nov 12 16:10:11 localhost CROND[509141]: (root) CMDOUT (TIME: 10 - Removing files older than 30 days on initiator replica for conflict backup deletion.)
Nov 12 16:10:11 localhost CROND[509141]: [94B blob data]
Nov 12 16:10:11 localhost CROND[509141]: (root) CMDOUT (TIME: 10 - Directory cleanup complete on initiator replica.)
Nov 12 16:10:11 localhost CROND[509141]: [444B blob data]
Nov 12 16:10:11 localhost CROND[509141]: [86B blob data]
Nov 12 16:10:12 localhost CROND[509141]: [69B blob data]
Nov 12 16:10:12 localhost CROND[509141]: (root) CMDOUT (TIME: 11 - Removing files older than 30 days on initiator replica for softdelete deletion.)
Nov 12 16:10:12 localhost CROND[509141]: [94B blob data]
Nov 12 16:10:12 localhost CROND[509141]: (root) CMDOUT (TIME: 11 - Directory cleanup complete on initiator replica.)
Nov 12 16:10:12 localhost CROND[509141]: [439B blob data]
Nov 12 16:10:13 localhost CROND[509141]: [86B blob data]
Nov 12 16:10:14 localhost CROND[509141]: [450B blob data]
Nov 12 16:10:14 localhost CROND[509141]: (root) CMDEND (/usr/local/bin/osync.sh /etc/osync/ftp_sync.conf)

Same hardware as in case #248

**Comment by deajan** [comment]
I have no real idea what happens here. I'll get back to you tomorrow once I have setup a test machine

**Comment by Turranius** [comment]
Thanks, but this is low priority I guess. I was hoping it was a "oh just use this switch" kinda thing. No rush!

**Comment by Turranius** [comment]
Actually, I found similar issues when googling. It seems it types blob data when there are unprintable output. Using journalctl -a allows you to see what it is actually printing.
https://dba.stackexchange.com/questions/216958/sql-server-logs-blob-data-viewable-with-journalctl
https://bbs.archlinux.org/viewtopic.php?id=149617

Here is a snippet of journalctl -a

Nov 15 10:32:01 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - -------------------------------------------------------------)
Nov 15 10:32:01 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - Tue Nov 15 10:32:01 CET 2022 - osync 1.2 script begin.)
Nov 15 10:32:01 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - -------------------------------------------------------------)
Nov 15 10:32:01 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - Sync task [ftp_site_only] launched as syncuser@*hostname* (PID 1402857))
Nov 15 10:32:01 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - Checking minimum disk space in local replica [/glftpd/site/].)
Nov 15 10:32:02 localhost CROND[1402827]: (root) CMDOUT (TIME: 0 - Checking minimum disk space in remote replica [/glftpd/site/].)
Nov 15 10:32:03 localhost CROND[1402827]: (root) CMDOUT (TIME: 2 - Starting synchronization task.)
Nov 15 10:32:03 localhost CROND[1402827]: (root) CMDOUT (TIME: 2 - Creating initiator replica file list [/glftpd/site/].)
Nov 15 10:32:03 localhost CROND[1402827]: (root) CMDOUT (TIME: 2 - Creating target replica file list [/glftpd/site/].)
Nov 15 10:32:08 localhost CROND[1402827]: (root) CMDOUT ( [-)  
Nov 15 10:32:14 localhost CROND[1402827]: (root) CMDOU [\]  )
Nov 15 10:32:20 localhost CROND[1402827]: (root) CM [|)  
Nov 15 10:32:25 localhost CROND[1402827]: (root) CMDOU)[/]  
Nov 15 10:32:30 localhost CROND[1402827]: (root) CMDOUT ( [\)  
Nov 15 10:32:35 localhost CROND[1402827]: (root) CMDOU [|]  )
Nov 15 10:32:40 localhost CROND[1402827]: (root) CM [/)  
Nov 15 10:32:45 localhost CROND[1402827]: (root) CMDOU)[-]  
Nov 15 10:32:50 localhost CROND[1402827]: (root) CMDOUT ( [|)  
Nov 15 10:32:56 localhost CROND[1402827]: (root) CMDOU [/]  )
Nov 15 10:33:01 localhost CROND[1402827]: (root) CM [-)  
Nov 15 10:33:06 localhost CROND[1402827]: (root) CMDOU)[\]  
Nov 15 10:33:11 localhost CROND[1402827]: (root) CMDOUT ( [/)  
Nov 15 10:33:16 localhost CROND[1402827]: (root) CMDOU [-]  )
Nov 15 10:33:21 localhost CROND[1402827]: (root) CM [\)  
Nov 15 10:33:26 localhost CROND[1402827]: (root) CMDOU)[|]  
Nov 15 10:33:31 localhost CROND[1402827]: (root) CMDOUT ( [-)  
Nov 15 10:33:36 localhost CROND[1402827]: (root) CMDOU [\]  )
Nov 15 10:33:42 localhost CROND[1402827]: (root) CM [|)  
Nov 15 10:33:47 localhost CROND[1402827]: (root) CMDOU)[/]  
Nov 15 10:33:52 localhost CROND[1402827]: (root) CMDOUT ( [\)  
Nov 15 10:33:57 localhost CROND[1402827]: (root) CMDOU [|]  )
Nov 15 10:34:02 localhost CROND[1402827]: (root) CM [/)  
Nov 15 10:34:07 localhost CROND[1402827]: (root) CMDOUTIME: 126 - Creating initiator replica deleted file list.)
Nov 15 10:34:07 localhost CROND[1402827]: (root) CMDOUT (TIME: 126 - Creating target replica deleted file list.)
Nov 15 10:34:07 localhost CROND[1402827]: (root) CMDOUT (TIME: 126 - Updating target replica.)
Nov 15 10:34:12 localhost CROND[1402827]: (root) CMDOUT ( [-)  
Nov 15 10:34:17 localhost CROND[1402827]: (root) CMDOU [\]  )
Nov 15 10:34:22 localhost CROND[1402827]: (root) CM [|)  
Nov 15 10:34:27 localhost CROND[1402827]: (root) CMDOU)[/]  
Nov 15 10:34:32 localhost CROND[1402827]: (root) CMDOUT ( [\)  
Nov 15 10:34:37 localhost CROND[1402827]: (root) CMDOU [|]  )

**Comment by deajan** [comment]
Ohh... It seems that I indeed had seen that incident before.
Run with `--errors-only` so the CLI spinner won't be shown, and so there will be no systemd blobs.

**Comment by deajan** [comment]
Mind to give me your systemd unit file content ?

**Comment by Turranius** [comment]
For? I'm running osync from crontab at the moment.

**Comment by deajan** [comment]
Okay... I'll probably add a `--non-interactive` switch for that since `--errors-only` does more.

**Comment by deajan** [comment]
`--non-interactive` option added in v1.3 final
