### ISSUE TITLE
Example config has both compression options enabled

### ISSUE THREAD

**Issue by jovanlanik** [deajan/osync#251]
The example config file has both compression options enabled (SSH_COMPRESSION and RSYNC_COMPRESS) while the comment suggests one or the other should be disabled, is this intentional?
A lot of people might copy the example and miss the comment. Maybe a more reasonable default should be included in the example config.

**Comment by deajan** [comment]
Your're totally right. And rsync compression is preferable to ssh compression as it also has compression exclusions.
Done in master.
Thanks.
