### ISSUE TITLE
Explanation of file attributes that appear on log

### ISSUE THREAD

**Issue by NightOwlCoder** [deajan/osync#252]
Is there an explanation anywhere about the attributes, like `f.st.......` show in the logs?
I'm having some files duplicated from time to time and i was wondering if those attributes could help me find why.

```
TIME: 14 - Truncated list:
>f.st....... .obsidian.jobsite.m1/app.json
>f..t....... .obsidian.jobsite.m1/appearance.json
>f.st....... .obsidian.jobsite.m1/workspace.json
>f..t....... .obsidian.jobsite.m1/plugins/obsidian-git/data.json
>f..t....... .obsidian.jobsite.m1/plugins/recent-files-obsidian/data.json
>f++++++++++ jobsite/._.DS_Store
>f++++++++++ jobsite/OnCall/._.DS_Store
>f.st....... jobsite/OnCall/Scaling.md
>f.st....... jobsite/OnCall/overrides.md
.d..t....... jobsite/OnCall/TARA_attachments/
>f.st....... jobsite/career/2023.md
>f..t....... pessoAll/learning/.DS_Store
```

My script syncs a Mac folder to a Windows VM exposed folder that is under iCloud sync. iCloud because I need my notes on an iPad.

**Comment by deajan** [comment]
These are rsync logs. Please check out the rsync docs to find out what characters represent what attributes.

**Comment by NightOwlCoder** [comment]
Just to help our fellow users, I'm pasting the formatted [man page](https://manpages.org/rsync) below:

The "%i" escape has a cryptic output that is 11 letters long. The general format is like the string **YXcstpoguax**, where **Y** is replaced by the type of update being done, **X** is replaced by the file-type, and the other letters represent attributes that may be output if they are being modified.

The update types that replace the **Y** are as follows:

-   A **<** means that a file is being transferred to the remote host (sent).
-   A **>** means that a file is being transferred to the local host (received).
-   A **c** means that a local change/creation is occurring for the item (such as the creation of a directory or the changing of a symlink, etc.).
-   A **h** means that the item is a hard link to another item (requires **--hard-links**).
-   A **.** means that the item is not being updated (though it might have attributes that are being modified).
-   A ***** means that the rest of the itemized-output area contains a message (e.g. "deleting").

The file-types that replace the **X** are: **f** for a file, a **d** for a directory, an **L** for a symlink, a **D** for a device, and a **S** for a special file (e.g. named sockets and fifos).

The other letters in the string above are the actual letters that will be output if the associated attribute for the item is being updated or a "." for no change. Three exceptions to this are: (1) a newly created item replaces each letter with a "+", (2) an identical item replaces the dots with spaces, and (3) an unknown attribute replaces each letter with a "?" (this can happen when talking to an older rsync).

The attribute that is associated with each letter is as follows:

-   A **c** means either that a regular file has a different checksum (requires **--checksum**) or that a symlink, device, or special file has a changed value. Note that if you are sending files to an rsync prior to 3.0.1, this change flag will be present only for checksum-differing regular files.
-   A **s** means the size of a regular file is different and will be updated by the file transfer.
-   A **t** means the modification time is different and is being updated to the sender's value (requires **--times**). An alternate value of **T** means that the modification time will be set to the transfer time, which happens when a file/symlink/device is updated without **--times** and when a symlink is changed and the receiver can't set its time. (Note: when using an rsync 3.0.0 client, you might see the **s** flag combined with **t** instead of the proper **T** flag for this time-setting failure.)
-   A **p** means the permissions are different and are being updated to the sender's value (requires **--perms**).
-   An **o** means the owner is different and is being updated to the sender's value (requires **--owner** and super-user privileges).
-   A **g** means the group is different and is being updated to the sender's value (requires **--group** and the authority to set the group).
-   The **u** slot is reserved for future use.
-   The **a** means that the ACL information changed.
-   The **x** means that the extended attribute information changed.

One other output is possible: when deleting files, the "%i" will output the string "*deleting" for each item that is being removed (assuming that you are talking to a recent enough rsync that it logs deletions instead of outputting them as a verbose message).
