### ISSUE TITLE
Option to disable ssh banner

### ISSUE THREAD

**Issue by 40417256** [deajan/osync#253]
**Describe the bug**
My target host has ssh banner enabled. The banner is displayed in the logs and on screen

**To Reproduce**
in /etc/ssh/sshd_config add:
Banner /etc/ssh/sshd_banner
in  /etc/ssh/sshd_banner add some text
restart ssh server
run osync banner is diplayed at ever ssh connection

**Expected behavior**
Ability to disable banners being displayed

**Environment (please complete the following information):**
Ubuntu 22.04

** fix 
Add option in in configuration
SHH_DISABLE_BANNER=yes

Add in code:
If error output is required 
`SSH_CMD="$(type -p ssh) -o LogLevel=error $SSH_COMP -i $SSH_RSA_PRIVATE_KEY $SSH_OPTS $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT"`

If error output NOT required (ie only return code from ssh)
`SSH_CMD="$(type -p ssh) -q $SSH_COMP -i $SSH_RSA_PRIVATE_KEY $SSH_OPTS $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT"`

**Comment by deajan** [comment]
I'm not really sure what your fix does, where is `SSH_DISABLE_BANNER` coded ?

**Comment by 40417256** [comment]
It is not coded, I am requesting that you add the option to disable ssh banners in your code because when you rune the tool the banner will be displayed at every connection (on screen or logs) and the script will always return it failed (but it did not). running with -q will disable ssh banners being displayed and the return script does not return and error anymore

**Comment by deajan** [comment]
Sorry for the really late reply.
If that's still an issue, just use `SSH_OPTIONAL_ARGS` in config file where you'll add `-q`

**Comment by 40417256** [comment]
Thank you sir.

16 June 2023: osync v1.3 release

Would be nice to make releases more often since I do not usually work with Master/Dev code.

Eric

**Comment by deajan** [comment]
osync is a time greedy project, which doesn't give me a penny back, so it's quite low priority.
Releases are done whenever I have time, but I admit that v1.3 was really overdue.
