### ISSUE TITLE
install.sh does not work

### ISSUE THREAD

**Issue by Kaze1027** [deajan/osync#256]
**Describe the bug**
The install.sh did nothing.

**To Reproduce**
1. I'm using Ubuntu22.04 LTS
2. Follow the guide steps in README:
```
$ git clone -b "stable" https://github.com/deajan/osync
$ cd osync
$ bash install.sh
```
4. And install.sh exit with message:"In order to make usage statistics, the script would like to connect to http://instcount.netpower.fr?program=osync&version=1.2&os=Linux%205.15.0-73-generic%20x86_64%20x86_64%20GNU%2FLinux%20%28%22Ubuntu%22%20%2222.04.2%20LTS%20%28Jammy%20Jellyfish%29%22%29&action=install
No data except those in the url will be send. Allow [Y/n] y
".

**Expected behavior**
It should installs the osync.

**Deviated behavior**
It did nothing.

**Logs**
Please send logs of what happens.
Here is the logs:
```
root@mapserver-CM:~/osync# ./install.sh 
Copied [sync.conf.example.new] to [/etc/osync].
Copied [exclude.list.example.new] to [/etc/osync].
Copied [osync.sh] to [/usr/local/bin].
Set file permissions to [755] on [/usr/local/bin/osync.sh].
Set file ownership on [/usr/local/bin/osync.sh] to [root:root].
Copied [osync-batch.sh] to [/usr/local/bin].
Set file permissions to [755] on [/usr/local/bin/osync-batch.sh].
Set file ownership on [/usr/local/bin/osync-batch.sh] to [root:root].
Copied [ssh_filter.sh] to [/usr/local/bin].
Set file permissions to [755] on [/usr/local/bin/ssh_filter.sh].
Set file ownership on [/usr/local/bin/ssh_filter.sh] to [root:root].
Copied [osync-srv@.service] to [/lib/systemd/system].
Created [osync-srv] service in [/lib/systemd/system] and [/etc/systemd/user].
Can be activated with [systemctl start SERVICE_NAME@instance.conf] where instance.conf is the name of the config file in /etc/osync.
Can be enabled on boot with [systemctl enable osync-srv@instance.conf].
In userland, active with [systemctl --user start osync-srv@instance.conf].
osync installed. Use with /usr/local/bin/osync

If connecting remotely, consider setup ssh filter to enhance security.

In order to make usage statistics, the script would like to connect to http://instcount.netpower.fr?program=osync&version=1.2&os=Linux%205.15.0-73-generic%20x86_64%20x86_64%20GNU%2FLinux%20%28%22Ubuntu%22%20%2222.04.2%20LTS%20%28Jammy%20Jellyfish%29%22%29&action=install
No data except those in the url will be send. Allow [Y/n] y

```

**Environment (please complete the following information):**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Additional context**
I tried to find it:
```
root@mapserver-CM:~/osync# /usr/local/bin/osync
-bash: /usr/local/bin/osync: No such file or directory
root@mapserver-CM:~/osync# find / -name osync
/etc/osync
/root/osync
root@mapserver-CM:~/osync# /etc/osync/
-bash: /etc/osync/: Is a directory
root@mapserver-CM:~/osync# /root/osync/
-bash: /root/osync/: Is a directory
```
Does the installation script has expired?

**Comment by deajan** [comment]
Well, read the logs, it installed into `/usr/local/bin/osync.sh` ;)

**Comment by deajan** [comment]
Btw, you used stable intead of master, which wasn't v1.3 until now.
Please git update and reinstall again to get last version.

**Comment by Kaze1027** [comment]
BTW, I'm wondering how to sync some files from folder, sometimes I just want sync one or two of my folder.

**Comment by deajan** [comment]
Well that's not a usecase osync handles.
You can still accomplish this by setting `OPTIONAL_RSYNC_ARGS=--include='*.pdf'` for example.
Arguments can be found on rsync man.
