### ISSUE TITLE
Running osync on a  2xnode active/active webserver cluster, in daemon mode

### ISSUE THREAD

**Issue by alokispandey** [deajan/osync#259]
Hi,
Thanks for the great work..! I find this tool very useful for our setup. 
Besides for one of the use case,
I am trying to set up synchronization between two standalone nodes behind a load balancer running a web server to form a cluster. Since we had limitations on data replication at the storage level, I needed to enable bi-directional sync from the OS layer.
Consider the OSYNC-daemon mode limitation where there is **a considerable delay in picking changes committed to the destination replica**. Would you advise running ossync on both nodes in daemon mode with Inotify, to sync the same files system let's say /var/www/html ?
**The goal is to sync cluster nodes as soon user makes any changes on either of the nodes.**

Suggest if there is any known issue/limitation/prerequisites which should be considered first.

**Comment by deajan** [comment]
To be honest, that's not really the target aimed. osync is a good solution for slow links, since it's not realtime, nor near-realtime.
You'd be probably better of using glusterfs if you want realtime sync.
You'll need at least three nodes (two real nodes + 1 arbiter) in order to achieve a quorum.
