### ISSUE TITLE
Install script has a problem

### ISSUE THREAD

**Issue by albersag** [deajan/osync#33]
root@kam02:/usr/src/osync# cat install.sh 
#!/usr/bin/env bash

SCRIPT_BUILD=2015070201

## Please adapt this to fit your distro needs

if [ "$(whoami)" != "root" ]
then
  echo "Must be run as root."
  exit 1
fi

mkdir /etc/osync
cp ./sync.conf /etc/osync/sync.conf.example
cp ./exclude.list.example /etc/osync
cp ./osync.sh /usr/local/bin
cp ./osync-batch.sh /usr/local/bin
cp ./ssh_filter.sh /usr/local/bin
cp ./osync-srv /etc/init.d
chmod 755 /usr/local/bin/osync.sh
chmod 755 /usr/local/bin/osync-batch.sh
chmod 755 /usr/local/bin/ssh_filter.sh
chown root:root /usr/local/bin/ssh_filter.sh
chmod 755 /usr/local/bin/osync-srv

chmod: no se puede acceder a «/usr/local/bin/osync-srv»: No existe el fichero o el directorio

i think something is missed

BR

**Comment by albersag** [comment]
Solved with

cp osync-srv /usr/local/bin/

and later

chmod 755 /usr/local/bin/osync-srv

**Comment by deajan** [comment]
Hello,

Actually this should be solved the following because osync-srv is the daemon part that should be in /etc/init.d so it can be launched as initV script.

```
chmod 755 /etc/init.d/osync-srv
```

Thanks.
