### ISSUE TITLE
enchancement?: detect folder renames

### ISSUE THREAD

**Issue by senorsmile** [deajan/osync#43]
E.g. 
- rename a folder on your local machine (the master)
- run a sync

Both locations end up correctly up to date, but what actually happens is that the new folder name and all its contents are transferred to the slave (i.e. the central server), and then the old folder is deleted.  It would be nice, especially for larger folders, to detect deleted folders in the presence of new folders, looking at the contents and simply renaming if appropriate.

**Comment by deajan** [comment]
This needs a helper service that detects renames (using inodes) and is on the list for v2.0 rewrite.
