### ISSUE TITLE
systemd service file

### ISSUE THREAD

**Issue by elbowz** [deajan/osync#46]
Could you provide the service file for systemd intestead of init.d?

**Comment by deajan** [comment]
It's a bit more complicated to abandon init.d because it launches one instance per config file found in /etc/osync.

What's the problem with using an old fashion init.d file ?
What are the advantages of using systemd here ?

**Comment by elbowz** [comment]
I see and understand could be complicated.

I have nothing against init.d but my dist (arch) and for what I know also others dists use systemd as default/standard.

Anyway, no matter...thanks for the great app!!

p.s. I guess could be more simple if osync-batch.sh support --on-change param

**Comment by deajan** [comment]
I'm using systemd myself, but life ain't easy :)
osync-batch.sh is designed to run sequential instances, so it won't run multiple daemons at once.
The problem with an osync systemd file is that it would only provide one pid file, whereas the init.d script provides one pid per instance.

I'll have a look on this once v1.1 is released.

**Comment by elbowz** [comment]
Thanks a lot.

I think could be useful and more simple create a parametrized (osync@param) systems profile with parm as conf file. This could be solve the issue of pids.

**Comment by elbowz** [comment]
Is it really simple, but what do you think?

```
[Unit]
Description=A robust two way (bidirectional) file sync script based on rsync with fault tolerance
After=time-sync.target local-fs.target 
Requires=time-sync.target local-fs.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/osync.sh /etc/osync/%i.conf --on-changes

[Install]
WantedBy=multi-user.target
```

**Comment by deajan** [comment]
Seems not bad, but as I said there are more problems when using a systemd file.
I have to redirect logged errors to stderr so systemd journal will catch them.
I also have to modify the install.sh script to detect whether the distrib uses systemd or init.

I'm working on something right now, I'll commit once I have something working.

**Comment by elbowz** [comment]
If i have well understood systemd **Wants** meaning not strictly...so should be not a problem.

Anyway you can drop out and should behaviour like your init.d script file...I think

**Comment by deajan** [comment]
I'll commit in a minute, can you try if it works for you ?

**Comment by elbowz** [comment]
Waooo, is it just ready?

..but I'm sorry, I'm away (from my pc) now

**Comment by deajan** [comment]
Ready is not the word :) It's coded, but not well tested yet, and it's way too late right now to go for intensive tests.
Anyway, when you can test it, please use the install.sh script and tell me what OS you're using.

**Comment by elbowz** [comment]
Ahaha...Of course, thanks!

P.s. Arch Linux is my os
Il 29 mar 2016 23:01, "Orsiris de Jong" <notifications@github.com> ha
scritto:

**Comment by elbowz** [comment]
sorry for the delayed answer...

well, the new version works like a charm :)
I think you have missed the tag "v1.1" in the git repository (following your readme)

if you like you could add also a systemd unit file to `/etc/systemd/user` path for allow to enable in "user space".

The issue that remain is that the service not always start when there is a connection available, so I guess you could add a timeout (or number of retries) to the ping functionality.

**Comment by deajan** [comment]
Tried to copy the systemd service file to /etc/systemd/user and login with a standard user.
Got ```==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===```

Also, I don't understand what you mean by your last sentence. The service starts regardless of successfully ping or not, it will only log an error.

Btw; didn't tag v1.1 yet because I had to deal with a party breaking bug before.
I'm testing and will soon have to release v1.1

I'd be glad to make the systemd file better until then.

**Comment by elbowz** [comment]
> Tried to copy the systemd service file to /etc/systemd/user and login with a standard user.
Got ==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===

Strange... if you have a copy of unit there the user can enable the daemon:
```systemctl --user enable osync-srv@file.cong```

> Also, I don't understand what you mean by your last sentence. The service starts regardless of successfully ping or not, it will only log an error.

Yeah, but after that fail and exit and don't wait that the system go online, isn't it?

> Btw; didn't tag v1.1 yet because I had to deal with a party breaking bug before.
I'm testing and will soon have to release v1.1

I have done a speedy test, and `.delete` folder seems don't works...but I can mistake

**Comment by deajan** [comment]
Well, systemctl --user [something] works on Fedora 23 but not on CentOS 7, but this is not unit file dependant but has to do with permissions on dbus.
I added a userland unit file for which I had to remove the ```Requires=time-sync.target local-fs.target``` directive because it made service launch file under F23, see commit https://github.com/deajan/osync/commit/c70563a63623f0b6d215c9ca38e40476deb4a807
I also added logging to home directory for userland service.

For the .delete folder, indeed there was an infamous typo fixed here https://github.com/deajan/osync/commit/335d94367fed105e4e59c8ba41029a126d207daf

Still thinking about the ping thing. Do you want osync to check for internet connectivity before starting ?

**Comment by elbowz** [comment]
> Still thinking about the ping thing. Do you want osync to check for internet connectivity before starting ?

yeah, it's good...but if the check fail the daemon fail? is it restart?

**Comment by deajan** [comment]
Main osync daemon starts and stays loaded until ended, normally spanning child osync instances that may fail. I've just tested it, the daemon stays loaded without internet, and executes a new child instance after WAIT_MAX seconds defined in config.

Can you give me some details so I may be able to reproduce the problem ?

**Comment by deajan** [comment]
Fixed, internet checks weren't supposed to be included in the daemon mode.
Can you confirm everything works for you ?

**Comment by elbowz** [comment]
Works like a charm, great work! :+1:

**Comment by deajan** [comment]
Thanks for all the feedback.
I'm pretty close to a good release now :)
