### ISSUE TITLE
Connect to rsyncd (not only to rsync via SSH) on the remote slave

### ISSUE THREAD

**Issue by Larx** [deajan/osync#47]
Reading the docs I understand that osync only uses SSH to connect to a remote server. However, rsync also offers the option to run as a server (--daemon option). I prefer this option, as here the other devices syncing to the server do not need login credentials, but only permissions to access the server.

The rsync usage seems to be pretty much the same, only the URI is different from SSH connections.

Would it be possible to adapt osync to this kind of rsync server?

**Comment by deajan** [comment]
Osync uses ssh to run commands before and after sync steps, so it won't run with rsyncd only.
