### ISSUE TITLE
Synchronization left both master and slave in broken states. Rollback?

### ISSUE THREAD

**Issue by seanmavley** [deajan/osync#49]
I did a master folder to slave folder sync earlier today. Didn't bother to check if everything went all.

Came back this evening, and majority of both the master and slave files and folders are missing. How do I recover, or go back to a previous state? 

The folders involved completed with success, so absolutely no idea why the missing syncs. I checked the deleted folders in the hidden osync dir, and under the deleted folder, I see most of the missing files, with some folders with empty content.

Is there anyway I can recover my stuff?

**Comment by deajan** [comment]
First of all, there is no way osync deletes your files unless an external deletion happened and osync propagates deletions on the other replica, and even in this case it will soft delete them.
Check the osync log file for details.

To restore your files, just copy the files from .osync_workdir/deleted back to your replica.

**Comment by seanmavley** [comment]
Thanks for quick response. 

If I deleted them manually, the files would have been in my Trash. They're not there.

To restore the files, the .osync_workdir/deleted was my first go to. Surprisingly, the files in there are not complete, the one osync is so-called assuming I've deleted.

Many of the files in folders in the osync deleted folder are missing. I'm looking at over 10 Gig of multimedia data lost, without a trace. 

Here's the log file: http://pastebin.com/HNcrT5zK
The 'Education' and 'Watchtower' folders are the only ones that were left inconsistent, although they reported successful in the logs.

**Comment by deajan** [comment]
From what I've read in the log, eg ```
TIME: 8 - Cannot move /media/khophi/khophiData/Education/LYVEN Proposal Nov 2015.docx to deletion directory.``` you may have a permission problem on some files.

Sorry to hear you lost files, but again, osync DOES NOT DELETE files by itself.
You may check your drives SMART status, and system stability.
Recover your files by using a livecd with photorec or testdisk.

**Comment by bittorf** [comment]
this is the content from osync.sync_laptop_sylvia.log
```
TIME: 8 - Creating initiator replica file list [/home/sylvia/].
TIME: 8 - Creating target replica file list [/tank/bastian/privat/backup/sylvia/home/sylvia/].
TIME: 9 - (CRITICAL):Cannot create replica file list in [/tank/bastian/privat/backup/sylvia/home/sylvia/].
TIME: 9 - (WARN):Command was [/usr/bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 -zz --skip-compress=gz/xz/lz/lzma/lzo/rz/jpg/mp3/mp4/7z/bz2/rar/zip/sfark/s7z/ace/apk/arc/cab/dmg/jar/kgb/lzh/lha/lzx/pak/sfx --no-whole-file  -p -o -g --executability  --exclude ".osync_workdir"   -e "/usr/bin/ssh -C -i /home/sylvia/.ssh/id_rsa  -p 443" --list-only bastian@bwireless.mooo.com:"/tank/bastian/privat/backup/sylvia/home/sylvia/" 2> "/tmp/osync.treeList.target.error.31883.20181113T070001.107400822" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.target.31883.20181113T070001.107400822"].
TIME: 9 - (WARN):Command output
Warning: Identity file /home/sylvia/.ssh/id_rsa not accessible: No such file or directory.
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.2]
TIME: 11 - (ERROR):Could not unlock target remote replica.
TIME: 11 - (WARN):Command Output:
Warning: Identity file /home/sylvia/.ssh/id_rsa not accessible: No such file or directory.
Host key verification failed.
TIME: 11 - (ERROR):osync finished with errors.
TIME: 11 - (ERROR):Cannot send mail (neither mutt, mail, sendmail, sendemail, mailsend (windows) or pfSense mail.php could be used).
```

**Comment by bittorf** [comment]
this is the content from a file 'osync.log'
```
TIME: 0 - (CRITICAL):Cannot load configuration file [/home/sylvia/.osync.conf]. Cannot start.
[ a lot of the same line ]
```
seems this is already since some weeks.
the laptop mostly used for browsing, so I did not recognized the problem...

**Comment by deajan** [comment]
I am not aware of a data eating problem like this.
Please open a new issue since this is probably unrelated and two years old.
osync.log is the basic log file until a config file is loaded, so that's not of big use.

Please only post FULL logs so investigation is possible.
I can think of a synthetic problem if osync cannot create the afterwards file list, but i need more info.
