### ISSUE TITLE
/usr/local/bin/osync.sh: line 778: [: -ne: unary operator expected

### ISSUE THREAD

**Issue by ValdisVitolins** [deajan/osync#52]
Run with commit 39c60d5
Actual line is:
```
....
 if [ $log_time -ne $SECONDS ]; then
...
```
Probably it should be:
```
 if [ $log_time -lt $SECONDS ]; then
```

**Comment by deajan** [comment]
Line 778 should stay with operator -ne, or osync would output the still running message every second.
The actual line that can produce the error is line 769 that is
```
local log_ttime=0
```
but should be
```
local log_time=0
```
