### ISSUE TITLE
File-based locking is not atomic when locking remote directory

### ISSUE THREAD

**Issue by allter** [deajan/osync#56]
I've run into this when I set MIN_WAIT=5 and used two initiator scripts running in --on-changes mode. :)

As I looked into code, the file-based locking is implemented using first trying to read remote lock (trying to delete it if it is stale lock), and then creating it using "echo pid | tee lock ".

With this approach two racing initiator scripts can both ensure that there is no lock at target, but then simply write to it and continue to work. The lock file will contain PID of the last script who performed "tee lock". 

This issue is not very important if the clocks on all three parties (two racing initiators and one target) are well synchronized. But if they not, and if the user edits more than one copy, then the final version after osync`ing may have inconsistent changes.

It is wise to implement locking in atomic fashion. As I briefly googled, this is done using making directories instead of lock files although this is not secure if the lock dir is situated on a NFS file system.

**Comment by deajan** [comment]
Sorry, I don't really get it here.
Two racing initiator scripts using the same target won't "overlap" because of the lock file. The initiator won't remove an existing lockfile on target unless FORCE_STRANGER_LOCK_RESUME=yes is set in config file.
So the first initiator to write the lock file will prevent the second from launching the sync task.

**Comment by allter** [comment]
Here is how osync does it now (at master), but v1.1 should be similar:
TIME: 26 - cmd: /usr/bin/ssh -C -i /home/allter/.ssh/id_rsa  guest@router-debian -p 22 "if [ -f \"/home/guest/Asus/osync/osync
ed_dir/.osync_workdir/lock\" ]; then cat \"/home/guest/Asus/osync/osynced_dir/.osync_workdir/lock\"; fi" > "/tmp/osync._CheckL
ocksRemote.8493"
TIME: 29 - Locked replica on [/home/allter/.osync/osynced_dir/.osync_workdir/lock].
TIME: 29 - 9486 is alive
TIME: 29 - 9487 is alive
TIME: 29 - cmd: /usr/bin/ssh -C -i /home/allter/.ssh/id_rsa  guest@router-debian -p 22 "echo 8493@sync_test |  tee \"/home/guest/Asus/osync/osynced_dir/.osync_workdir/lock\"" > /dev/null 2>&1
TIME: 29 - 9486 exited okay with 0

The check for lock file at remote actually happens at TIME: 26. If other process check lock file before the next command is completed at remote (tee \"/home/guest/Asus/osync/osynced_dir/.osync_workdir/lock\""), that latter process will continue as if there were not competitors. "tee" will just silently overwrite the lock file. As you see, I have very slow remote so there are 3 seconds for another process to intervene.

**Comment by deajan** [comment]
I see. Well there's nothing I can think of that I could do to relove this.
If it takes 3 seconds for your remote system to lock the target, and in the meanwhile another initiator locks it, it will win.

But let me ask you a question. If I happen to understand your setup, you've done this:

```
Initiator A-----------\
                             -------Target C
Initiator B-----------/
```

Isn't this setup easier (and also would solve your lock problem) ?
```
Target A-----------\
                             ------- Initiator C
Target B-----------/
```

**Comment by allter** [comment]
Not easier for my particular setup. And plus, one of the initiators can be run both from hardware machine and from a virtual machine (dual boot configuration). So it could be tricky for Initiator C to find this Target. Plus, the C side now has very old linux kernel that does not support inotify, so I need to poll Target C frequently. C side is resource-constrained, so I would not like to make it poll A and B while they could be offline. And C is the only party which is expected to be online so it's logical to poll it from A and B.

Ideally, I want to achieve a "poor man's on-premises cloud-hosting cluster", but without all that heavyweight OpenStack-like software. And synchronized directories is one of its components.

**Comment by allter** [comment]
About locking. I've fixed it for myself at https://github.com/allter/osync/tree/atomic_locking using bash's "set -o noclobber". It's not a "pull ready" but I woud like to see comments. The remote side patch is at https://github.com/allter/osync/commit/658c270376e9b8bc287f647fc2fa795d64fb6b7e . After I wrote this I figured that instead of checking $COMMAND_SUDO it's easier to write something like this: 

'$COMMAND_SUDO' bash -c "set -o noclobber; echo '$SCRIPT_PID@$INSTANCE_ID' > '$lockfile' ";

(with right quotes, off course). Because if sysadmins allow to "sudo tee", they can allow "sudo bash" as well.

**Comment by deajan** [comment]
I've looked at your solution. It's not bad, I didn't know the noclobber option.
Some drawbacks:
You need to recover the commad output in order to get the error message into the logfile.
Please apply patches to dev/n_osync.sh instead of osync.sh, which is generated.

I'll probably add the INSTANCE_ID variable to lockfiles in order to find who currently locks the replica later. Let me know when you have something merge ready.

**Comment by allter** [comment]
Error message is already good in logfiles. The command output is not very necessary because of checking of "$?".  For example (this is message about local lock; for remote lock it is almost the same): 

osync/osync.sh: line 1468: /home/allter/.osync/osynced_dir/.osync_workdir/lock: cannot overwrite existing file
 /!\ ERROR in osync/osync.sh: Near line 1468, exit code 1
 /!\ ERROR in osync/osync.sh: Near line 1463, exit code 1
TIME: 33 - Could not create lock file [/home/allter/.osync/osynced_dir/.osync_workdir/lock].
TIME: 33 - Removed local replica lock.
TIME: 33 - cmd: /usr/bin/ssh -C -i /home/allter/.ssh/id_rsa  guest@router-debian -p 22 "if [ -f \"/home/guest/Asus/osync/osynced_dir/.osync_workdir/lock\" ]; then  rm -f \"/home/guest/Asus/osync/osynced_dir/.osync_workdir/lock\"; fi" > "/tmp/osync._UnlockReplicasRemote.23432" 2>&1
TIME: 38 - Removed remote replica lock.

**Comment by allter** [comment]
> I'll probably add the INSTANCE_ID variable to lockfiles in order to find who currently locks the replica later. Let me know when you have something merge ready.

I did not understand, what you are talking about. "@$INSTANCE_ID" is already written in a lock file. But it is only used in _CheckLocksRemote, not in _CheckLocksLocal. Checking it in _CheckLocksLocal may be important if the intiatior replica can be used as target in a server-less setups.

**Comment by deajan** [comment]
Error message does not say what happened (you don't know whether the lock file could not be written because you don't have write permission, or because of noclobber option.
As for INSTANCE_ID, it's about making log messages more clear.

I'll wait for your PR (to dev/n_osync.sh) in order to rewrite those bits.

**Comment by deajan** [comment]
Any time to rebase your PR ?

**Comment by deajan** [comment]
Rewrote patch and included in latest beta.
