### ISSUE TITLE
Trying to set remote attributes although params are set to "no"

### ISSUE THREAD

**Issue by ionutdumitru** [deajan/osync#58]
Hello,

I've started using osync recently and I am trying to sync 2 large folders containing images grouped in some subfolders.

Initiator folders are owned by root:root and are 777.
Target folders are owned by syncuser:www-data and are 777.

Attributes are set to no:
PRESERVE_ACL=no
PRESERVE_XATTR=no

The connection is done through ssh + key from a dedicated user.

Initiator and target folders are the same = /mnt/storage/tezaur-amanet/

From the log:

TIME: 0 - -------------------------------------------------------------
TIME: 0 -  Tue Aug  9 12:53:32 EEST 2016 - osync 1.1.1 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [appsrv] launched as syncuser@appsrv (PID 66787)
TIME: 19 - Checking minimum disk space in [/mnt/storage/tezaur-amanet/].
TIME: 19 - Checking minimum disk space on target [/mnt/storage/tezaur-amanet/].
TIME: 46 - Starting synchronization task.
TIME: 46 - WARN:WARNING: Trying to resume aborted osync execution on 2016-08-09 12:50:50.353990066 +0300 at task [noresume]. [0] previous tries.
TIME: 46 - Creating initiator replica file list [/mnt/storage/tezaur-amanet/].
TIME: 173 - Creating target replica file list [/mnt/storage/tezaur-amanet/].
TIME: 384 - Creating target replica file list [/mnt/storage/tezaur-amanet/].
TIME: 226 - Creating initiator replica deleted file list.
TIME: 437 - Creating initiator replica deleted file list.
TIME: 227 - Creating target replica deleted file list.
TIME: 438 - Creating target replica deleted file list.
TIME: 227 - Getting list of files that need updates.
TIME: 438 - Getting list of files that need updates.
TIME: 244 - Getting ctimes for pending files on initiator.
TIME: 244 - Getting ctimes for pending files on target.
TIME: 455 - Getting ctimes for pending files on initiator.
TIME: 455 - Getting ctimes for pending files on target.
TIME: 250 - Updating file attributes on initiator not required
TIME: 250 - Updating target replica.
TIME: 461 - Updating file attributes on initiator not required
TIME: 461 - Updating target replica.
TIME: 319 - Updating target replica succeded.
TIME: 319 - Updating initiator replica.
TIME: 530 - Updating target replica succeded.
TIME: 530 - Updating initiator replica.
TIME: 543 - CRITICAL:Updating initiator replica failed. Stopping execution.
TIME: 332 - CRITICAL:Updating initiator replica failed. Stopping execution.
TIME: 336 - Rsync output:
rsync: chgrp "/mnt/storage/tezaur-amanet/contracts" failed: Operation not permitted (1)
rsync: chgrp "/mnt/storage/tezaur-amanet/contracts/C0212000203" failed: Operation not permitted (1)
rsync: chgrp "/mnt/storage/tezaur-amanet/contracts/C0212000203/C0212000203_01.jpg" failed: Operation not permitted (1)
rsync: chgrp "/mnt/storage/tezaur-amanet/contracts/C0212000204" failed: Operation not permitted (1)

Is this working correctly? If so, what is the config problem?

Thank you,
Ionut Dumitru

**Comment by deajan** [comment]
PRESERVE_ACL is used for ACLs, not standard owner and groups permissions.

Try latest osync commit with:
PRESERVE_PERMISSIONS=no
PRESERVE_OWNER=no
PRESERVE_GROUP=no
PRESERVE_EXECUTABILITY=no
PRESERVE_ACL=no
PRESERVE_XATTR=no

**Comment by ionutdumitru** [comment]
Thank you, I tried and apparently the sync is working without trying to set permissions. Will be watching for the backport on 1.1-maint.

**Comment by deajan** [comment]
Sorry, no feature addition to backport. Stick with v1.2, today's version should be as stable as v1.1 until I introduce new untested stuff.
