### ISSUE TITLE
installing osync doesn't copy sync.conf to /etc/osync

### ISSUE THREAD

**Issue by hortimech** [deajan/osync#59]
I installed osync and then went to edit /etc/osync/sync.conf, only to find it didn't exist. Examining the install.sh code revealed this:

function CopyExampleFiles {
	if [ -f "./sync.conf.example" ]; then
		cp "./sync.conf.example" "/etc/$PROGRAM/sync.conf.example"
	fi

	if [ -f "./host_backup.conf.example" ]; then
		cp "./host_backup.conf.example" "/etc/$PROGRAM/host_backup.conf.example"
	fi

	if [ -f "./exlude.list.example" ]; then
		cp "./exclude.list.example" "/etc/$PROGRAM"
	fi

	if [ -f "./snapshot.conf.example" ]; then
		cp "./snapshot.conf.example" "/etc/$PROGRAM/snapshot.conf.example"
	fi
}

There is no 'sync.conf.example' file in the tarball, just 'sync.conf'
The only one that is there is 'exclude.list.example'

This is on version 1.1.1

**Comment by deajan** [comment]
Thanks for reporting.
sync.conf.example and sync.conf are actually the same files. You may just use the sync.conf from the archive and copy it to /etc/osync meanwhile.

**Comment by hortimech** [comment]
On Sat, 27 Aug 2016 05:15:20 -0700
Orsiris de Jong <notifications@github.com> wrote:

> Thanks for reporting.
> sync.conf.example and sync.conf are actually the same files. You may
> just use the sync.conf from the archive and copy it to /etc/osync
> meanwhile.
> 

Well, yes, I worked that out, but you need to fix it in the install.sh
script.

Rowland

**Comment by deajan** [comment]
Well, yes, I'll have to rename sync.conf to sync.conf.example. Again, thanks for reporting.

**Comment by deajan** [comment]
Relased v1.1.2 today containing two fixes plus sync.conf.example rename.
