### ISSUE TITLE
function GetRemoteOS silently failing

### ISSUE THREAD

**Issue by senorsmile** [deajan/osync#6]
Getting the following error when trying to run osync with a remote slave

TIME: 241 - Max soft execution time exceeded for task.
/usr/local/bin/osync: line 405: [: 241: unary operator expected
/usr/local/bin/osync: line 405: [: 242: unary operator expected
/usr/local/bin/osync: line 405: [: 243: unary operator expected

and on and on.  

The problem appears to be on line 332 of osync.sh: 
                eval "$SSH_CMD \"uname -spio\" > $RUN_DIR/osync_remote_os_$SCRIPT_PID 2>&1"
should have a '&' at the end in order for the next line
                child_pid=$!
to succeed.  

Adding the ampersand seems to fix the issue.

**Comment by deajan** [comment]
Thanks for your fix.
I added additionnal ampersands to fix empty $child_pid variables;
