### ISSUE TITLE
Add ssh password option

### ISSUE THREAD

**Issue by extremeshok** [deajan/osync#66]
Sometimes its not possible to use ssh keys, ie certain chrooted/rssh based accounts

I am aware of the disadvantages of using passwords for ssh logins, however most of them are mitigated with 64 random character passwords and fail2ban/denyhosts for login bruteforce protection.

I would like to add the functionality and submit a pull request, would you be willing to include it ?

I do not want to spent time forking, coding, testing and then you are not willing to have the functionality for some obscure reason.

Thanks

**Comment by deajan** [comment]
ROFL for the obsucre reason :)
As long as the sync.conf file explicitly says that it is a bad idea to do so, I'm willing to include it.

It should be added to the config file and as command line argument like --rsakey and it's equivalent in config file.

Please only edit files in dev and use dev/merge.sh as osync.sh and other sh files in root are autogenerated.

**Comment by deajan** [comment]
Added SSH_PASSWORD_FILE option with latest commit.
