### ISSUE TITLE
add support for termux (android)

### ISSUE THREAD

**Issue by tristan-k** [deajan/osync#69]
> Termux is a terminal emulator and Linux environment bringing powerful terminal access to Android. 

Please add support for installing  osync with `install.sh` in a termux envirionment on Android. There is a documentation available at https://termux.com/linux.html

> - Common folders such as /bin, /usr/, /var and /etc does not exist.
> - Termux installs its packages in a folder exposed through the $PREFIX environment variable (with e.g. binaries in $PREFIX/bin, and configuration in $PREFIX/etc).
> - Shared libraries are installed in $PREFIX/lib, which are available from binaries due to Termux setting the $LD_LIBRARY_PATH environment variable. These may clash with Android system binaries in /system/bin, which may force LD_LIBRARY_PATH to be cleared before running system binaries.
> - Besides the file system being different, Termux is running as a single-user system without root - each Android app is running as its own Linux user, so running commands inside Termux may not interfere with other installed applications.

**Comment by deajan** [comment]
There's already a $FAKEROOT variable in recent install.sh.
Can you try running FAKEROOT=$PREFIX install.sh and see if it works ?

**Comment by deajan** [comment]
Closed in favor of #71
