### ISSUE TITLE
osync changes folder owners to root

### ISSUE THREAD

**Issue by RubyDrus** [deajan/osync#83]
Dear programmers,

First things first, thanks for creating and making osync. It does has some nice functions superior to other sync programs.

However, I encountered a problem while testing my set-up: osync changed the owner of my files to root. This is annoying as other programs, like R running on my data lose the ability to work with the data due to missing rights.

Here is my setup: I have one mega folder named "projects". I have three machines, a Ubuntu desktop for computational power, a nas for backup and server sharing purposes and a laptop for remote access to my data.

My main folder "projects" is on my Ubuntu machine in my home directory. osync is tasked via crontab to synchronise to /mnt/nas which itself is connected to the nas server. From there I can mount it on my laptop via vpn. 
It does sound complicated and cumbersome but it suits my needs as I always have two physical copies on two different machines, have a my data on my Ubuntu machine (main computer) without the need to transfer data through the network and I can access it through my laptop without any interference. osync is perfect in that regard, that I bidirectional sync the data between my laptop (via nas) and my Ubuntu machine. 
I hope that makes sense to you. If you have recommendations to make it easier, they are more than welcome!

In any case, I believe the problem is that I have the nas mounted in /mnt/nas from where I osync to my home.

It would immensely helpful if you could assist me with that!

Best wishes,
Ruben

**Comment by deajan** [comment]
Hello,

osync normally ownership so unless you have modified the default PRESERVE values in config file, it should work.
Nevertheless, depending on what FS you are syncing, you may loose ownership.
What FS does your nas use ?

**Comment by deajan** [comment]
Closing this because of insufficient info. Feel free to re open if you can provide additional data.
