### ISSUE TITLE
Memory consumption with large amoutn of files to sync

### ISSUE THREAD

**Issue by vdg1** [deajan/osync#89]
Hi,

I'm trying to use the script on my NAS (1GB RAM, 512MB swap) on a large set of files (photo library). Currently all actions I try with osync are in dry run mode. When building the file list osync stops with:
"/usr/local/bin/osync.sh: fork: Cannot allocate memory"
Are there any means to optimize osyncs memory usage (lke split the sync process into multiple sets of file lists, ...)?

**Comment by deajan** [comment]
You actually get that error when log says the following ?

>  Creating initiator replica file list [/path/to/replica]. 

If yes, run the following which is basically a stripped down version of the file list function
```rsync -rltd -8 --list-only /path/to/files 2> "error.log" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "list.log"```

Also, please give me ```free -h``` info and file / directory counts so I can simulate the problem.

**Comment by vdg1** [comment]
Hi Deajan,

thanks for the super fast response!

 "find /data/Pictures/ -type f | wc -l" 
returns 
238959

"free -h" 
returns
             total       used       free     shared    buffers     cached
Mem:          988M       901M        87M       264K       1.8M       421M
-/+ buffers/cache:       477M       510M
Swap:         511M       194M       317M

Your command line returned no errors in error.log.

**Comment by deajan** [comment]
Well, maybe 87M to run on that large filebase isn't enough :)
Can you run latest RC1 debug version with environment variable ```_PARANOIA_DEBUG=yes``` and post output ?

**Comment by deajan** [comment]
Tried to run osync against my filebase today.
"find /storage -type -f | wc -l" returned
652577

The rsync process eats 126M of memory while running on that fileset.
No problems so far.

There's one question that remains.
If rsync eats that amout of memory, treeList may eat the same while piping rsync output into different grep / awk commands.
Maybe sending rsync output to a tmp file and then cat that file to grep / awk commands might lower memory usage, but I definitly need more input here if you want me to have a closer look.

**Comment by deajan** [comment]
Closing because no news, no bug resolution. Feel free to reopen if needed.
