### ISSUE TITLE
turn off soft delete?

### ISSUE THREAD

**Issue by lilmike** [deajan/osync#9]
Hi,
I use osync to synchronize my two web server's web directories together, and I have run into a problem:
When osync syncs, it does a soft delete, which means that any files my web server (running wordpress, nginx, mysql) deletes, don't get deleted on the other end.
Could it be possible to have an option to turn off soft deletes (if there is one, I'm just not seeing it).
Thanks,
-Michael.

**Comment by deajan** [comment]
Hello Michael,

If you run osync with a conf file, there is a SOFT_DELETE=yes value you may set to no on line 102.
If you run quick sync tasks directly from command line, you may use the following:
```
$ SOFT_DELETE=no /path/to/osync.sh --master=/whatever --slave=/somethingelse
```

Regards,
Ozy.

**Comment by lilmike** [comment]
Hi,
Thanks. I figured it would be in the config file, so now thanks for 
letting me know that it can be done from the command line. Consider this 
closed.
-Michael.
