### ISSUE TITLE
With crontab,osync doesn't work

### ISSUE THREAD

**Issue by liyong6351** [deajan/osync#90]
Hi deajan:
    First I think your project is great ! Recently I follow the document step by step. It work with shell command well no matter sync between  local-local or local-remote. But when i config it in crontab as a task,I find the task work well but file not sync, can you give me some help

My OS version is Ubuntu 14.0.5 LTS , and the crontab task config like this:
*/1 * * * * root /home/liyong/tools/osync/osync.sh /etc/osync/sync-local.conf --silent 

The config file just as the attachment
[sync-local.txt](https://github.com/deajan/osync/files/762781/sync-local.txt)

**Comment by liyong6351** [comment]
I am sorry the content's format is so confusion，and you can find config whole in the attachment

**Comment by deajan** [comment]
I assume that you did chmod +x the osync.sh file ?
What do the logs say ?

**Comment by liyong6351** [comment]
Yes,I give the osync.sh all the privilege,and run the crontab's user is root . I read the document say the log file default lay in /var/log/osync_version_SYNC_ID.log。But sadly with the crontab task the log file never create~

**Comment by deajan** [comment]
In most cases, crontab doesn't work because of bogus syntax, double check for newlines or spaces.
If there is no log file, than osync hasn't even run so it's up to your crontab.
Try replace the osync crontab entry with ```echo "test" >> /root/file``` in order to check if it will run.

**Comment by liyong6351** [comment]
Oh,I am sorry maybe I didn't describe the problem completely.The crontab task run well,I use tail -f /var/log/cron.log can monitor the log like this 'Feb  9 16:21:01 liyong-ThinkPad-X1-Carbon-3rd CRON[25544]: (root) CMD (root /home/liyong/tools/osync/osync.sh /etc/osync/sync-local.conf --silent >/dev/null 2>&1) '。**But** the osync.sh run with the config file never create the log。That is to say the crontab is well but osync is not ok~ By the way, I config the crontab just like the command written in the osync's Document~

**Comment by deajan** [comment]
Looool !
See your log "CMD (root /home/liyong/tools/osync/osync.sh /etc/osync/sync-local.conf --silent >/dev/null 2>&1) " ?
Remove "root" from the command.
Actually the crontab syntax in the doc is an example and fits Redhat. Debian / Ubuntu don't want username. I will have a note about that.

**Comment by liyong6351** [comment]
Great~It's my fault that experience in Linux so poor.

**Comment by deajan** [comment]
No problem. Have fun :)
