### ISSUE TITLE
Option to disable alerts on unstable builds

### ISSUE THREAD

**Issue by Torbe** [deajan/osync#94]
I'm running the latest RC to be able to use the new:
```
PRESERVE_PERMISSIONS=no
PRESERVE_OWNER=no
PRESERVE_GROUP=no
PRESERVE_EXECUTABILITY=no
```

Now I'm wondering how to _not_ get notified by mail on every sync because unstable builds create an alert. I just need alerts on errors. Would be cool to have an option for that.

**Comment by deajan** [comment]
You may set ```IS_STABLE=yes``` directly in osync.sh header

**Comment by Torbe** [comment]
Thanks! That worked!
