### ISSUE TITLE
Performance issues / Any idea?

### ISSUE THREAD

**Issue by jensengelmann** [deajan/osync#97]
Hi,

first of all I want to thank you for developing such a great tool. I didn't find any good master-master-replication tool for linux.

We have big performance problems when syncing our two file servers. The creation of the file list took six hours. The actual replication speed is fine. Since we want to do a daily replication, this is a big problem for us.

Our specs:
- we're syncing a ZFS filesystem on two different machines over ssh
- we got about 630000 files in about 62000 directories with a total of 3 TB
- we're syncing full ACLs and xattr
- using latest stable osync release
- we got a decent processor (XEON E3-1240v5) and a decent amount of RAM (32 GB, upgradable if needed)

Here (https://github.com/deajan/osync/issues/89#issuecomment-278333719) you wrote that you're acutally also syncing about 600000 files without any problems.

Do you have any idea why osync is that slow? Is there a problem with the ZFS file system?

Thanks in advance for your help and input!

**Comment by deajan** [comment]
As a matter of fact, my file pool is actually running on ZoL 0.6.5.9 so I don't think the problem is ZFS related, still, there could be zfs performance issues but this would be out of sight of this issue.

Can you give me some details like ?
- OS and kernel version
- osync output using ```_PARANOIA_DEBUG=yes ./debug_osync.sh [your options]```
- identify the bottleneck with top ? ram ? cpu ? disk io (see wa%) ?
- disk usage & cpu usage while performing the file list creation (per process)
- presence of ```comm``` utility

Also, I gave a test commandline here https://github.com/deajan/osync/issues/89#issuecomment-277517428 to virtually create the file list in bash. Mind to run it ? Maybe prefix it with time ? And give per process cpu usage ?

Regards.

**Comment by jensengelmann** [comment]
I will run the osync debug tomorrow... but I can answer some of your questions now:
- Ubuntu 16.04 (Server), Kerner 4.4.0-72-generic x86_64
- almost no disk i/o but first rsync and than bash and than again rsync got the cpu (one core only!?) at 100% (pretty much all the time while creating lists and so on)
- there was always some 5gb memory available
- comm utility is installed
- I did the create the list virtually like you recommended - it ran thru blazingly fast (under 1 minute) and created the list porperly
  - I did a `cat | wc -l`  on the list which returned 673456 lines - this ist the sum of files and folders inside my storage mount... so it seems to work

**Comment by deajan** [comment]
Can you give me the output of the paranoia_debug line stated above ?

**Comment by jensengelmann** [comment]
I got a sync running right now... can I nevertheless run the paranoia debug right now or should I wait until the original sync is finished?

**Comment by deajan** [comment]
Please let the other sync finish before running a test.
The paranoia option is set as environment variable and must be run with the debug version of osync, eg:
```_PARANOIA_DEBUG=yes ./debug_osync.sh /path/to/my.conf```

**Comment by jensengelmann** [comment]
I did a little anonymization... host = host, remote = remote

```
Entering function [WaitForTaskCompletion].
TIME: 1 - treeList arguments: [Argument 1: /mnt/host/xxx/] [Argument 2: initiator] [Argument 3: -tree-current-osync_xxx_xxx]
TIME: 1 - treeList arguments: [Argument 1: /mnt/remote/xxx/] [Argument 2: target] [Argument 3: -tree-current-osync_xxx_xxx]
TIME: 1 - WaitForTaskCompletion arguments: [Argument 1: 6264;6265] [Argument 2: 0] [Argument 3: 0] [Argument 4: .05] [Argument 5: 1801] [Argument 6: false] [Argument 7: true] [Argument 8: false]
TIME: 1 - Creating initiator replica file list [/mnt/host/xxx/].
TIME: 1 - Creating target replica file list [/mnt/remote/xxx/].
TIME: 1 - RSYNC_CMD: /usr/bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 -zz --skip-compress=gz/xz/lz/lzma/lzo/rz/jpg/mp3/mp4/7z/bz2/rar/zip/sfark/s7z/ace/apk/arc/cab/dmg/jar/kgb/lzh/lha/lzx/pak/sfx --no-whole-file  -p -o -g --executability -A -X  --exclude ".osync_workdir"   --list-only "/mnt/host/xxx/" 2> "/tmp/osync.treeList.initiator.error.6111.20170426T012740.307758776" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.initiator.6111.20170426T012740.307758776"
TIME: 1 - Entering function [CheckConnectivity3rdPartyHosts].
TIME: 1 -Entering function [CheckConnectivityRemoteHost].
TIME: 1 -RSYNC_CMD: /usr/bin/rsync --rsync-path="__(o_O)__ rsync" -rltD -8 -zz --skip-compress=gz/xz/lz/lzma/lzo/rz/jpg/mp3/mp4/7z/bz2/rar/zip/sfark/s7z/ace/apk/arc/cab/dmg/jar/kgb/lzh/lha/lzx/pak/sfx --no-whole-file  -p -o -g --executability -A -X  --exclude ".osync_workdir"   -e "/usr/bin/ssh -C -i /root/.ssh/id_rsa  -p 22" --list-only root@osync-xxx:"/mnt/remote/xxx/" 2> "/tmp/osync.treeList.target.error.6111.20170426T012740.307758776" | (grep -E "^-|^d|^l" || :) | (awk '{$1=$2=$3=$4="" ;print substr($0,5)}' || :) | (awk 'BEGIN { FS=" -> " } ; { print $1 }' || :) | (grep -v "^\.$" || :) | sort > "/tmp/osync.treeList.target.6111.20170426T012740.307758776"
```
...now I'm waiting again...

(PS: Can I interrupt the sync?)

**Comment by deajan** [comment]
I'd need the full (anonymized) log in order to have a clue about the problem. Could you pastebin it or send it per mail ?

**Comment by deajan** [comment]
Just added a basic performance profiler to the debug version.
Please use latest git version (add --dry in order to not alter anything if you want) and have a run with ```_PARANOIA_DEBUG=yes _PERF_PROFILER=yes ./debug_osync.sh /path/your.conf```

**Comment by deajan** [comment]
Problem comes from rsync < 3.1.2 which has performance issues with xattr tranfers.
