### ISSUE TITLE
Segmentation fault in macOS Sierra

### ISSUE THREAD

**Issue by lifepillar** [deajan/osync#98]
I have just tried a local-local sync with the current master and v1.2 on macOS. In both cases, synchronization is performed, but then I get a segmentation fault:

```
./osync.sh --initiator=./source_replica --target=./target_replica 
TIME: 1 - -------------------------------------------------------------
TIME: 1 - Wed May 24 12:33:46 CEST 2017 - osync 1.2 script begin.
TIME: 1 - -------------------------------------------------------------
TIME: 1 - Sync task [quicksync_task] launched as me@MyMac.local (PID 20740)
TIME: 1 - Checking minimum disk space in local replica [./source_replica/].
TIME: 1 - Checking minimum disk space in local replica [./target_replica/].
TIME: 1 - Starting synchronization task.
TIME: 1 - Creating target replica file list [./target_replica/].
TIME: 1 - Creating initiator replica file list [./source_replica/].
TIME: 1 - Creating initiator replica deleted file list.
TIME: 1 - Creating target replica deleted file list.
TIME: 1 - Updating target replica.
TIME: 1 - Updating target replica succeded.
TIME: 1 - Updating initiator replica.
TIME: 1 - Updating initiator replica succeded.
TIME: 1 - Propagating deletions to initiator replica.
TIME: 1 - Propagating deletions to target replica.
TIME: 1 - Creating initiator replica file list [./source_replica/].
TIME: 1 - Creating target replica file list [./target_replica/].
TIME: 2 - Finished synchronization task.
TIME: 2 - Running conflict backup cleanup.
TIME: 2 - Running soft deletion cleanup.
TIME: 2 - Removing files older than 30 days on initiator replica for softdelete deletion.
TIME: 2 - Removing files older than 30 days on target replica for softdelete deletion.
TIME: 2 - File cleanup complete on initiator replica.
TIME: 2 - File cleanup complete on target replica.
TIME: 2 - Directory cleanup complete on initiator replica.
TIME: 2 - Directory cleanup complete on target replica.
TIME: 2 - osync finished.
Segmentation fault: 11
```

**Comment by deajan** [comment]
I am no mac specialist, but segfault 11 seems to happen with recursion.
There aren't recursive functions in osync so my best guess it that something in your bash profile might be bogus somewhere.
Could you try to temporarily rename your .bashrc file and test again ?

See https://stackoverflow.com/questions/41084393/osx-bash-command-gives-segmentation-fault-11 for more info.

If this doesn't solve the issue, please have a run with:
_PARANOIA_DEBUG=yes debug_osync.sh [your parameters]

**Comment by lifepillar** [comment]
I have found that the problem comes from the version of `pgrep` I am using (from [Homebrew](https://brew.sh)), which apparently ignores the `-P` flag, resulting in `pgrep -P $PID` to print the list of *all* process IDs. If I use the OS's version of `pgrep`, everything works fine.

You might want to consider making this snippet more robust:

```sh
function KillChilds {
	local pid="${1}" # Parent pid to kill childs
	local self="${2:-false}" # Should parent be killed too ?

	# Warning: pgrep does not exist in cygwin, have this checked in CheckEnvironment
	if children="$(pgrep -P "$pid")"; then
		for child in $children; do
			KillChilds "$child" true
		done
	fi
```

by checking that `children` does not contain `$pid`. Anyway, this is not a bug in `osync`, so sorry for the noise.

**Comment by deajan** [comment]
Yep, good idea to have an additional check here. Re-opening this to add to todo list.

**Comment by deajan** [comment]
Added warning in https://github.com/deajan/osync/commit/fe210877dc776b350ccedcd1f4776b2c231b3fa0

Would you mind testing this with the bogus version of pgrep you had ?
Or give me details about that pgrep so I can add something to the documentation ?

Thanks

**Comment by lifepillar** [comment]
>Would you mind testing this with the bogus version of pgrep you had ?

It still segfaults in the same way. It might happen because `KillChilds` is passed a non-existing `$pid`: I have noticed that if I call `pgrep -P` with a non-existent process ID, it outputs all process IDs. So, you should also check whether `$pid` exists before calling `pgrep`.

>give me details about that pgrep

It is version 0.4pre1 installed by [Homebrew](https://github.com/Homebrew/homebrew-core). Here is the script: https://github.com/Homebrew/homebrew-core/blob/master/Formula/proctools.rb. I see that it applies a few patches and, in particular, one to `pgrep`. I'll try without that patch to see if it makes any difference.

**Comment by deajan** [comment]
Does it at least output "Bogus pgrep implementation" ?

**Comment by lifepillar** [comment]
>Does it at least output "Bogus pgrep implementation" ?

No, that's why I think  that`KillChilds` is called with a non-existent `$pid`.

I've tried to build Homebrew's proctools without the patch but it does not compile.

**Comment by lifepillar** [comment]
Btw, I've reported the issue with Homebrew's `pgrep` at https://github.com/Homebrew/homebrew-core/issues/14020.

**Comment by deajan** [comment]
I've updated osync with another "fool proof" test in KillChilds.
Btw there's a great chance that you actually didn't test the latest change because I didn't rebuild osync.sh (I rely on bootstrap.sh for tests). Rebuilt it, could you please test again ?

Also, what's the command in MacOS X to get the "good" pgrep ?
When I did tests on my virtual Mac install, I didn't have to install it.

**Comment by lifepillar** [comment]
Sorry, I didn't explain myself clearly. You should check that `$pid` is the ID of a running process, not only a valid process ID. With the current master I still get the same segmentation fault (and no “bogus” messages), but if I check for an existing process then osync exits without errors:

```sh
  if ps -p $pid >/dev/null; then  # if process $pid exists…
    if children="$(pgrep -P "$pid")"; then
      if [[ "$pid" == *"$children"* ]]; then
        Logger "Bogus pgrep implementation." "CRITICAL"
        children="${children/$pid/}"
      fi
      for child in $children; do
        KillChilds "$child" true
      done
    fi
  fi
```

>Also, what's the command in MacOS X to get the "good" pgrep ?

macOS (at least, Sierra) comes with `pgrep` in `/usr/bin`. That works fine with osync. The problematic version can be installed with the following command:

    brew install proctools

You need to first install [Homebrew](https://brew.sh), of course.

**Comment by deajan** [comment]
Okay, understand it better now.
Last fixes https://github.com/deajan/osync/commit/c2b24688ef157c223ba71d2a64541c29aa2ecb3a and https://github.com/deajan/osync/commit/11bd517982b45a505f189da5ec371e00b9bef609 should do the trick.

The KillChilds code is shared with other projects of which one uses some amounts of child processes that need to be terminated.
Moving the ```if kill -0 $pid``` command affected the case where a process finishes between two recursive calls. Had to keep that command twice, for the recursive call and the effective termination.
Now my functional tests are happy.

Should work on your setup, even if process termination can't work properly with bogus pgrep installed, which I can't detect easily.

**Comment by lifepillar** [comment]
Using `if kill -0 "$pid" > /dev/null 2>&1` still causes a segfault, but with`if ps -p "$pid" > /dev/null 2>&1` osync exits without errors. No idea why, I can't spot any difference between the two commands when I try them on the command line.

**Comment by deajan** [comment]
Well I can't use ```ps -p``` because it has some compatibility issues.
What does ```kill -0``` give with a non existent pid on your system ?

**Comment by lifepillar** [comment]
I have done some debugging and I have found that, after being called once with a valid (=existing) `$pid`, `KillChilds` is subsequently called with `$pid` equal to `0`.

Now, `kill -0 0` return exit code `0`, while `ps -p 0` returns exit code `1`. This explains why with `ps` it doesn't enter the conditional block.

**Comment by deajan** [comment]
Thank you for your patience and help. Added '0' to the list of invalid pids since I only checked it to be numeric and non empty until now.
This is still not a real fix for a bogus pgrep implementation, but more of a warning I'll document about.

Would you mind having a last test run ?

**Comment by lifepillar** [comment]
Ok, finally I see `(CRITICAL):Bogus pid given [0]` in the log. Returning from `KillChilds`, however, does not cause osync to exit. I guess you should force exit at that point (line 306).

**Comment by deajan** [comment]
Good to know at least it detects a problem now, at least.
I won't make KillChilds exit on error, a subfunction should never exit a program, that's a quite bad way of handling errors. I must know which KillChilds call affects the execution in order to see what error insn't catched well.
I guess at some point osync exits by itself and doesn't just stay like in waiting mode forever ?

Would you mind running the debug version so I get a clue of what happens ?
```_PARANOIA_DEBUG=yes debug_osync.sh [your_parameters]```

**Comment by lifepillar** [comment]
I seems it goes into an infinite loop. Here's the log: https://gist.github.com/lifepillar/940b846724071cb531fd2d0fe3b52bb9

**Comment by deajan** [comment]
I am puzzled that KillChilds is called with pid 0 in the first place.
Two questions:

1/ Would you mind changing line 2059 of debug_osync.sh from
```KillChilds $$ > /dev/null 2>&1```
to
```Logger "My pid is $SCRIPT_PID and $$" "NOTICE"
KillChilds $SCRIPT_PID > /dev/null 2>&1```

then run again with for the log ?

2/ Would you mind me having an ssh access to that system in order to debug ?

**Comment by lifepillar** [comment]
>I am puzzled that KillChilds is called with pid 0 in the first place.

It's the bogus `pgrep`, as usual:

```sh
$ pgrep -P 12345
0
50
90
...
```

I am wondering whether it is worth spending so much effort into a clearly buggy program. It is better to wait for https://github.com/Homebrew/homebrew-core/issues/14020 to be fixed. For me it's not a problem, since I can use macOS's `pgrep`.

>Would you mind me having an ssh access to that system in order to debug ?

Sorry, I cannot grant access to the system I'm using.

**Comment by deajan** [comment]
Indeed, I'm just trying to get to the bottom of my code, rendering it more robust.
Since I cannot see what really happens, I hardened the KillChilds function. 
Last commit https://github.com/deajan/osync/commit/2b163d385be3bc88b72c216f46ca27f0a4d96b2c also excludes 1 from valid pids since 1 is the root of all other processes.

I do think that this should end the recursion hell you're experiencing.
Mind for a very last debug run for this issue ?
```_PARANOIA_DEBUG=yes debug_osync.sh [your_parameters]```

**Comment by deajan** [comment]
Closed for inactivity.
